/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/auth/facebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with Facebook
         * @description Exchange a Facebook OAuth code for a session.
         */
        post: operations["auth-facebook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate with Google
         * @description Verify a Google ID token, create/update user, return session.
         */
        post: operations["auth-google"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description Deletes the current session and clears the session cookie.
         */
        post: operations["auth-logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current user
         * @description Returns the authenticated user. Requires session cookie.
         */
        get: operations["get-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update profile
         * @description Update the current user's display name and username. Requires session cookie.
         */
        patch: operations["update-me"];
        trace?: never;
    };
    "/api/plays/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming plays */
        get: operations["list-plays"];
        put?: never;
        /**
         * Create a play
         * @description Create a new play session. Requires authentication.
         */
        post: operations["create-play"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plays/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a play by ID */
        get: operations["get-play"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List venues with postal codes
         * @description Returns all resolved venues that have a postal code and coordinates. Useful for building venue selectors.
         */
        get: operations["list-venues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContactMethod: {
            type: string;
            value: string;
        };
        CreateInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/CreateInputBody.json
             */
            readonly $schema?: string;
            /** @description Contact methods */
            contacts?: components["schemas"]["ContactMethod"][] | null;
            /**
             * Format: int64
             * @description Number of courts
             */
            courts?: number;
            /**
             * @description Currency code
             * @default SGD
             */
            currency: string;
            /**
             * Format: int64
             * @description Duration in minutes (must be multiple of 15, max 300)
             */
            duration_minutes: number;
            /**
             * Format: int64
             * @description Fee in cents
             */
            fee?: number;
            /**
             * @description Game type
             * @enum {string}
             */
            game_type?: "doubles" | "singles" | "mixed_doubles" | "";
            /**
             * @description Gender preference
             * @enum {string}
             */
            gender_pref?: "all" | "male_only" | "female_only" | "";
            /** @description Maximum level code */
            level_max?: string;
            /** @description Minimum level code */
            level_min?: string;
            /**
             * Format: int64
             * @description Maximum number of players
             */
            max_players?: number;
            /**
             * Format: int64
             * @description Available slots
             */
            slots_left?: number;
            /**
             * @description Sport type
             * @enum {string}
             */
            sport: "badminton" | "tennis" | "football" | "pickleball";
            /** @description Start time in RFC3339 format */
            starts_at: string;
            /**
             * @description IANA timezone, e.g. Asia/Singapore
             * @default Asia/Singapore
             */
            timezone: string;
            /** @description Venue name (free text) */
            venue: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        FacebookInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FacebookInputBody.json
             */
            readonly $schema?: string;
            /** @description OAuth authorization code from Facebook callback */
            code: string;
            /** @description The redirect_uri used in the OAuth flow (must match) */
            redirect_uri: string;
        };
        FacebookOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/FacebookOutputBody.json
             */
            readonly $schema?: string;
            session_token: string;
            user: components["schemas"]["User"];
        };
        GoogleInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GoogleInputBody.json
             */
            readonly $schema?: string;
            /** @description Google ID token from GIS Sign-In */
            credential: string;
        };
        GoogleOutputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/GoogleOutputBody.json
             */
            readonly $schema?: string;
            session_token: string;
            user: components["schemas"]["User"];
        };
        ListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["VenuePublic"][] | null;
        };
        PagePlayPublic: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PagePlayPublic.json
             */
            readonly $schema?: string;
            /** @description Whether there are more results after this page */
            has_more: boolean;
            items: components["schemas"]["PlayPublic"][] | null;
            /** @description Opaque cursor; pass as cursor to get the next page */
            next_cursor?: string;
            /**
             * Format: int64
             * @description Total number of matching results across all pages
             */
            total: number;
        };
        PlayPublic: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PlayPublic.json
             */
            readonly $schema?: string;
            contacts: components["schemas"]["ContactMethod"][] | null;
            /** Format: int64 */
            courts?: number;
            created_at: string;
            created_by?: string;
            creator_display_name?: string;
            creator_photo_url?: string;
            creator_username?: string;
            currency: string;
            ends_at: string;
            /** Format: int64 */
            fee?: number;
            /** @enum {string} */
            game_type?: "doubles" | "singles" | "mixed_doubles";
            /** @enum {string} */
            gender_pref?: "all" | "male_only" | "female_only";
            host_name: string;
            /** Format: int64 */
            id: number;
            level_max?: string;
            level_min?: string;
            /** @enum {string} */
            listing_type: "play" | "sell_booking";
            /** Format: int64 */
            max_players?: number;
            meta: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            slots_left?: number;
            source?: string;
            source_group?: string;
            /** @description Deep link to original message, e.g. t.me/group/123 */
            source_link?: string;
            source_message_id?: string;
            /** @description Link to sender's Telegram profile, e.g. t.me/username */
            source_sender_link?: string;
            /** @enum {string} */
            sport: "badminton" | "tennis" | "football" | "pickleball";
            starts_at: string;
            timezone: string;
            updated_at: string;
            /** @description Raw venue name as extracted from the message */
            venue: string;
            /** Format: int64 */
            venue_id?: number;
            /** Format: double */
            venue_latitude?: number;
            /** Format: double */
            venue_longitude?: number;
            /** @description Display name: resolved venue name, or raw venue name, or 'No venue' */
            venue_name: string;
            venue_postal_code?: string;
        };
        UpdateInputBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/UpdateInputBody.json
             */
            readonly $schema?: string;
            /** @description User's display name */
            display_name: string;
            /** @description Optional unique handle */
            username?: string;
        };
        User: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/User.json
             */
            readonly $schema?: string;
            contact_info?: string;
            created_at: string;
            display_name: string;
            email: string;
            id: string;
            photo_url?: string;
            sports_profile?: string;
            status: string;
            updated_at: string;
            username?: string;
        };
        VenuePublic: {
            /** Format: int64 */
            id: number;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            name: string;
            postal_code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "auth-facebook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FacebookInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FacebookOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-google": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GoogleInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GoogleOutputBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "auth-logout": {
        parameters: {
            query?: never;
            header?: {
                Cookie?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "update-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-plays": {
        parameters: {
            query?: {
                /** @description Filter by listing type */
                listing_type?: "play" | "sell_booking" | "";
                /** @description Filter by sport */
                sport?: "badminton" | "tennis" | "football" | "pickleball" | "";
                /** @description Filter by venue ID */
                venue_id?: number;
                /** @description Minimum level code (e.g. HB). Shows plays overlapping this range. */
                level_min?: string;
                /** @description Maximum level code (e.g. LI). Defaults to level_min if only level_min is set. */
                level_max?: string;
                /** @description Only include plays starting on or after this date (YYYY-MM-DD) */
                starts_after?: string;
                /** @description Reference latitude for distance sorting */
                lat?: number;
                /** @description Reference longitude for distance sorting */
                lng?: number;
                /** @description Opaque cursor from previous page */
                cursor?: string;
                /** @description Number of results per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagePlayPublic"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "create-play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateInputBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayPublic"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-play": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Play ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayPublic"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
