/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/plays/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List upcoming plays */
        get: operations["list-plays"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plays/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a play by ID */
        get: operations["get-play"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/venues/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List venues with postal codes
         * @description Returns all resolved venues that have a postal code and coordinates. Useful for building venue selectors.
         */
        get: operations["list-venues"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ContactMethod: {
            type: string;
            value: string;
        };
        ErrorDetail: {
            /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
            location?: string;
            /** @description Error message text */
            message?: string;
            /** @description The value at the given location */
            value?: unknown;
        };
        ErrorModel: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ErrorModel.json
             */
            readonly $schema?: string;
            /**
             * @description A human-readable explanation specific to this occurrence of the problem.
             * @example Property foo is required but is missing.
             */
            detail?: string;
            /** @description Optional list of individual error details */
            errors?: components["schemas"]["ErrorDetail"][] | null;
            /**
             * Format: uri
             * @description A URI reference that identifies the specific occurrence of the problem.
             * @example https://example.com/error-log/abc123
             */
            instance?: string;
            /**
             * Format: int64
             * @description HTTP status code
             * @example 400
             */
            status?: number;
            /**
             * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
             * @example Bad Request
             */
            title?: string;
            /**
             * Format: uri
             * @description A URI reference to human-readable documentation for the error.
             * @default about:blank
             * @example https://example.com/errors/example
             */
            type: string;
        };
        ListBody: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/ListBody.json
             */
            readonly $schema?: string;
            items: components["schemas"]["VenuePublic"][] | null;
        };
        PagePlayPublic: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PagePlayPublic.json
             */
            readonly $schema?: string;
            /** @description Whether there are more results after this page */
            has_more: boolean;
            items: components["schemas"]["PlayPublic"][] | null;
            /** @description Opaque cursor; pass as cursor to get the next page */
            next_cursor?: string;
            /**
             * Format: int64
             * @description Total number of matching results across all pages
             */
            total: number;
        };
        PlayPublic: {
            /**
             * Format: uri
             * @description A URL to the JSON Schema for this object.
             * @example https://example.com/schemas/PlayPublic.json
             */
            readonly $schema?: string;
            contacts: components["schemas"]["ContactMethod"][] | null;
            /** Format: int64 */
            courts?: number;
            created_at: string;
            currency: string;
            ends_at: string;
            /** Format: int64 */
            fee?: number;
            /** @enum {string} */
            game_type?: "doubles" | "singles" | "mixed_doubles";
            /** @enum {string} */
            gender_pref?: "all" | "male_only" | "female_only";
            host_name: string;
            /** Format: int64 */
            id: number;
            level_max?: string;
            level_min?: string;
            /** @enum {string} */
            listing_type: "play" | "sell_booking";
            /** Format: int64 */
            max_players?: number;
            meta: {
                [key: string]: unknown;
            };
            /** Format: int64 */
            slots_left?: number;
            source?: string;
            source_group?: string;
            /** @description Deep link to original message, e.g. t.me/group/123 */
            source_link?: string;
            source_message_id?: string;
            /** @description Link to sender's Telegram profile, e.g. t.me/username */
            source_sender_link?: string;
            /** @enum {string} */
            sport: "badminton" | "tennis" | "football" | "pickleball";
            starts_at: string;
            timezone: string;
            updated_at: string;
            venue: string;
            /** Format: int64 */
            venue_id?: number;
            /** Format: double */
            venue_latitude?: number;
            /** Format: double */
            venue_longitude?: number;
            venue_name?: string;
            venue_postal_code?: string;
        };
        VenuePublic: {
            /** Format: int64 */
            id: number;
            /** Format: double */
            latitude: number;
            /** Format: double */
            longitude: number;
            name: string;
            postal_code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "list-plays": {
        parameters: {
            query?: {
                /** @description Filter by listing type */
                listing_type?: "play" | "sell_booking" | "";
                /** @description Filter by sport */
                sport?: "badminton" | "tennis" | "football" | "pickleball" | "";
                /** @description Filter by venue ID */
                venue_id?: number;
                /** @description Only include plays starting on or after this date (YYYY-MM-DD) */
                starts_after?: string;
                /** @description Reference latitude for distance sorting */
                lat?: number;
                /** @description Reference longitude for distance sorting */
                lng?: number;
                /** @description Opaque cursor from previous page */
                cursor?: string;
                /** @description Number of results per page */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagePlayPublic"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "get-play": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Play ID */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayPublic"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
    "list-venues": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBody"];
                };
            };
            /** @description Error */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ErrorModel"];
                };
            };
        };
    };
}
