// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat.sql

package db

import (
	"context"
	"time"
)

const createChatMessage = `-- name: CreateChatMessage :one
INSERT INTO chat_messages (conversation_id, sender_user_id, body)
VALUES (?, ?, ?)
RETURNING id, conversation_id, sender_user_id, body, deleted_at, created_at
`

type CreateChatMessageParams struct {
	ConversationID string
	SenderUserID   string
	Body           *string
}

func (q *Queries) CreateChatMessage(ctx context.Context, arg CreateChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, createChatMessage, arg.ConversationID, arg.SenderUserID, arg.Body)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.Body,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createDMConversation = `-- name: CreateDMConversation :one
INSERT INTO chat_conversations (id, kind, dm_key)
VALUES (?, 'dm', ?)
ON CONFLICT(dm_key) DO UPDATE SET
    updated_at = chat_conversations.updated_at
RETURNING id, kind, play_id, dm_key, created_at, updated_at
`

type CreateDMConversationParams struct {
	ID    string
	DmKey *string
}

func (q *Queries) CreateDMConversation(ctx context.Context, arg CreateDMConversationParams) (ChatConversation, error) {
	row := q.db.QueryRowContext(ctx, createDMConversation, arg.ID, arg.DmKey)
	var i ChatConversation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PlayID,
		&i.DmKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDMParticipant = `-- name: CreateDMParticipant :exec
INSERT OR IGNORE INTO chat_dm_participants (conversation_id, user_id)
VALUES (?, ?)
`

type CreateDMParticipantParams struct {
	ConversationID string
	UserID         string
}

func (q *Queries) CreateDMParticipant(ctx context.Context, arg CreateDMParticipantParams) error {
	_, err := q.db.ExecContext(ctx, createDMParticipant, arg.ConversationID, arg.UserID)
	return err
}

const getChatConversation = `-- name: GetChatConversation :one
SELECT id, kind, play_id, dm_key, created_at, updated_at FROM chat_conversations
WHERE id = ?
`

func (q *Queries) GetChatConversation(ctx context.Context, id string) (ChatConversation, error) {
	row := q.db.QueryRowContext(ctx, getChatConversation, id)
	var i ChatConversation
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.PlayID,
		&i.DmKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatMessageWithSender = `-- name: GetChatMessageWithSender :one
SELECT
    m.id,
    m.conversation_id,
    m.sender_user_id,
    m.body,
    m.deleted_at,
    m.created_at,
    u.display_name AS sender_display_name,
    u.username AS sender_username,
    u.photo_url AS sender_photo_url
FROM chat_messages m
JOIN users u ON u.id = m.sender_user_id
WHERE m.id = ? AND m.conversation_id = ?
`

type GetChatMessageWithSenderParams struct {
	ID             int64
	ConversationID string
}

type GetChatMessageWithSenderRow struct {
	ID                int64
	ConversationID    string
	SenderUserID      string
	Body              *string
	DeletedAt         *time.Time
	CreatedAt         time.Time
	SenderDisplayName string
	SenderUsername    *string
	SenderPhotoUrl    *string
}

func (q *Queries) GetChatMessageWithSender(ctx context.Context, arg GetChatMessageWithSenderParams) (GetChatMessageWithSenderRow, error) {
	row := q.db.QueryRowContext(ctx, getChatMessageWithSender, arg.ID, arg.ConversationID)
	var i GetChatMessageWithSenderRow
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.Body,
		&i.DeletedAt,
		&i.CreatedAt,
		&i.SenderDisplayName,
		&i.SenderUsername,
		&i.SenderPhotoUrl,
	)
	return i, err
}

const getDMConversationPeer = `-- name: GetDMConversationPeer :one
SELECT
    other.id,
    other.display_name,
    other.username,
    other.photo_url,
    other.status
FROM chat_conversations c
JOIN chat_dm_participants mine
    ON mine.conversation_id = c.id
    AND mine.user_id = ?1
JOIN chat_dm_participants theirs
    ON theirs.conversation_id = c.id
    AND theirs.user_id <> ?1
JOIN users other ON other.id = theirs.user_id
WHERE c.id = ?2
  AND c.kind = 'dm'
`

type GetDMConversationPeerParams struct {
	ViewerID       string
	ConversationID string
}

type GetDMConversationPeerRow struct {
	ID          string
	DisplayName string
	Username    *string
	PhotoUrl    *string
	Status      string
}

func (q *Queries) GetDMConversationPeer(ctx context.Context, arg GetDMConversationPeerParams) (GetDMConversationPeerRow, error) {
	row := q.db.QueryRowContext(ctx, getDMConversationPeer, arg.ViewerID, arg.ConversationID)
	var i GetDMConversationPeerRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.PhotoUrl,
		&i.Status,
	)
	return i, err
}

const listChatMessages = `-- name: ListChatMessages :many
SELECT
    m.id,
    m.conversation_id,
    m.sender_user_id,
    m.body,
    m.deleted_at,
    m.created_at,
    u.display_name AS sender_display_name,
    u.username AS sender_username,
    u.photo_url AS sender_photo_url
FROM chat_messages m
JOIN users u ON u.id = m.sender_user_id
WHERE m.conversation_id = ?1
  AND (
    ?2 = 0
    OR m.id < ?2
  )
ORDER BY m.id DESC
LIMIT ?3
`

type ListChatMessagesParams struct {
	ConversationID string
	BeforeID       interface{}
	Limit          int64
}

type ListChatMessagesRow struct {
	ID                int64
	ConversationID    string
	SenderUserID      string
	Body              *string
	DeletedAt         *time.Time
	CreatedAt         time.Time
	SenderDisplayName string
	SenderUsername    *string
	SenderPhotoUrl    *string
}

func (q *Queries) ListChatMessages(ctx context.Context, arg ListChatMessagesParams) ([]ListChatMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listChatMessages, arg.ConversationID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChatMessagesRow
	for rows.Next() {
		var i ListChatMessagesRow
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.SenderUserID,
			&i.Body,
			&i.DeletedAt,
			&i.CreatedAt,
			&i.SenderDisplayName,
			&i.SenderUsername,
			&i.SenderPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDMConversationsByUser = `-- name: ListDMConversationsByUser :many
SELECT
    c.id,
    c.kind,
    c.play_id,
    c.created_at,
    c.updated_at,
    other.id AS other_user_id,
    other.display_name AS other_display_name,
    other.username AS other_username,
    other.photo_url AS other_photo_url,
    lm.id AS last_message_id,
    lm.sender_user_id AS last_message_sender_user_id,
    lm.body AS last_message_body,
    lm.deleted_at AS last_message_deleted_at,
    lm.created_at AS last_message_created_at,
    sender.display_name AS last_message_sender_display_name,
    sender.username AS last_message_sender_username,
    sender.photo_url AS last_message_sender_photo_url,
    (
        SELECT COUNT(*)
        FROM chat_messages unread
        LEFT JOIN chat_read_states rs
            ON rs.conversation_id = unread.conversation_id
            AND rs.user_id = ?1
        WHERE unread.conversation_id = c.id
          AND unread.sender_user_id <> ?1
          AND unread.deleted_at IS NULL
          AND unread.id > COALESCE(rs.last_read_message_id, 0)
    ) AS unread_count
FROM chat_conversations c
JOIN chat_dm_participants mine
    ON mine.conversation_id = c.id
    AND mine.user_id = ?1
JOIN chat_dm_participants theirs
    ON theirs.conversation_id = c.id
    AND theirs.user_id <> ?1
JOIN users other
    ON other.id = theirs.user_id
    AND other.status = 'active'
LEFT JOIN chat_messages lm
    ON lm.id = (
        SELECT id
        FROM chat_messages
        WHERE conversation_id = c.id
        ORDER BY id DESC
        LIMIT 1
    )
LEFT JOIN users sender ON sender.id = lm.sender_user_id
WHERE c.kind = 'dm'
  AND NOT EXISTS (
    SELECT 1 FROM user_blocks ub
    WHERE (ub.blocker_id = ?1 AND ub.blocked_id = other.id)
       OR (ub.blocker_id = other.id AND ub.blocked_id = ?1)
  )
ORDER BY COALESCE(lm.created_at, c.updated_at) DESC, c.id DESC
LIMIT ?2
`

type ListDMConversationsByUserParams struct {
	ViewerID string
	Limit    int64
}

type ListDMConversationsByUserRow struct {
	ID                           string
	Kind                         string
	PlayID                       *string
	CreatedAt                    time.Time
	UpdatedAt                    time.Time
	OtherUserID                  string
	OtherDisplayName             string
	OtherUsername                *string
	OtherPhotoUrl                *string
	LastMessageID                *int64
	LastMessageSenderUserID      *string
	LastMessageBody              *string
	LastMessageDeletedAt         *time.Time
	LastMessageCreatedAt         *time.Time
	LastMessageSenderDisplayName *string
	LastMessageSenderUsername    *string
	LastMessageSenderPhotoUrl    *string
	UnreadCount                  int64
}

func (q *Queries) ListDMConversationsByUser(ctx context.Context, arg ListDMConversationsByUserParams) ([]ListDMConversationsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDMConversationsByUser, arg.ViewerID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDMConversationsByUserRow
	for rows.Next() {
		var i ListDMConversationsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.PlayID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.OtherUserID,
			&i.OtherDisplayName,
			&i.OtherUsername,
			&i.OtherPhotoUrl,
			&i.LastMessageID,
			&i.LastMessageSenderUserID,
			&i.LastMessageBody,
			&i.LastMessageDeletedAt,
			&i.LastMessageCreatedAt,
			&i.LastMessageSenderDisplayName,
			&i.LastMessageSenderUsername,
			&i.LastMessageSenderPhotoUrl,
			&i.UnreadCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteChatMessageBySender = `-- name: SoftDeleteChatMessageBySender :one
UPDATE chat_messages
SET
    body = NULL,
    deleted_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?
  AND conversation_id = ?
  AND sender_user_id = ?
  AND deleted_at IS NULL
RETURNING id, conversation_id, sender_user_id, body, deleted_at, created_at
`

type SoftDeleteChatMessageBySenderParams struct {
	ID             int64
	ConversationID string
	SenderUserID   string
}

func (q *Queries) SoftDeleteChatMessageBySender(ctx context.Context, arg SoftDeleteChatMessageBySenderParams) (ChatMessage, error) {
	row := q.db.QueryRowContext(ctx, softDeleteChatMessageBySender, arg.ID, arg.ConversationID, arg.SenderUserID)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.SenderUserID,
		&i.Body,
		&i.DeletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const upsertChatReadState = `-- name: UpsertChatReadState :exec
INSERT INTO chat_read_states (conversation_id, user_id, last_read_message_id, read_at)
VALUES (?, ?, ?, strftime('%Y-%m-%d %H:%M:%S+00:00', 'now'))
ON CONFLICT(conversation_id, user_id) DO UPDATE SET
    last_read_message_id = max(chat_read_states.last_read_message_id, excluded.last_read_message_id),
    read_at = excluded.read_at
`

type UpsertChatReadStateParams struct {
	ConversationID    string
	UserID            string
	LastReadMessageID int64
}

func (q *Queries) UpsertChatReadState(ctx context.Context, arg UpsertChatReadStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertChatReadState, arg.ConversationID, arg.UserID, arg.LastReadMessageID)
	return err
}
