// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"openplays/server/internal/model"
)

type ChatConversation struct {
	ID        string
	Kind      string
	PlayID    *string
	DmKey     *string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ChatDmParticipant struct {
	ConversationID string
	UserID         string
	CreatedAt      time.Time
}

type ChatMessage struct {
	ID             int64
	ConversationID string
	SenderUserID   string
	Body           *string
	DeletedAt      *time.Time
	CreatedAt      time.Time
}

type ChatReadState struct {
	ConversationID    string
	UserID            string
	LastReadMessageID int64
	ReadAt            time.Time
}

type Play struct {
	ID                   string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ListingType          model.ListingType
	Sport                model.Sport
	GameType             *model.GameType
	HostName             string
	StartsAt             time.Time
	EndsAt               time.Time
	Timezone             string
	Venue                string
	LevelMin             *string
	LevelMax             *string
	LevelMinOrd          *int64
	LevelMaxOrd          *int64
	Fee                  *int64
	Currency             string
	MaxPlayers           *int64
	SlotsLeft            *int64
	Courts               *int64
	Contacts             model.Contacts
	GenderPref           *model.GenderPref
	Meta                 model.Meta
	Source               *string
	SourceSenderUsername *string
	SourceRawMessage     *string
	SourceMessageTime    *time.Time
	VenueID              *int64
	SourceMessageID      *string
	SourceGroup          *string
	SourceSenderName     *string
	CreatedBy            *string
	CancelledAt          *time.Time
	CancelledBy          *string
	Name                 *string
	Description          *string
	Visibility           model.PlayVisibility
	RequireWaitlist      bool
}

type PlayEvent struct {
	ID                 int64
	PlayID             string
	EventType          model.PlayEventType
	ActorUserID        *string
	ActorDisplayName   *string
	SubjectUserID      *string
	SubjectDisplayName *string
	ParticipantID      *int64
	Metadata           *string
	CreatedAt          time.Time
}

type PlayFavourite struct {
	UserID    string
	PlayID    string
	CreatedAt time.Time
}

type PlayHost struct {
	PlayID    string
	UserID    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type PlayParticipant struct {
	ID         int64
	PlayID     string
	UserID     *string
	GuestName  *string
	RatingCode *string
	RatingOrd  *int64
	Status     model.PlayParticipantStatus
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type PlayReview struct {
	ID             int64
	PlayID         string
	ReviewerUserID string
	RevieweeUserID string
	Rating         *int64
	Props          string
	Shoutout       *string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type PlayReviewPrompt struct {
	PlayID string
	UserID string
	SentAt time.Time
}

type RawMessage struct {
	ID              int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Source          string
	SenderUsername  string
	MessageText     string
	MessageTime     time.Time
	ContentHash     string
	Status          string
	RetryCount      int64
	NextRetryAt     *time.Time
	LastError       *string
	LlmResponse     *string
	SourceMessageID *string
	SourceGroup     *string
	SenderName      string
}

type Session struct {
	Token     string
	UserID    string
	ExpiresAt time.Time
	CreatedAt time.Time
}

type User struct {
	ID            string
	Email         string
	Username      *string
	DisplayName   string
	PhotoUrl      *string
	GoogleID      *string
	FacebookID    *string
	Status        string
	SportsProfile *string
	ContactInfo   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	OauthPhotoUrl *string
	AvatarKey     *string
	Bio           *string
	ProfileLinks  *string
}

type UserBlock struct {
	BlockerID string
	BlockedID string
	CreatedAt time.Time
}

type UserNotification struct {
	ID        string
	UserID    string
	Title     string
	Body      *string
	Url       *string
	Tag       *string
	Kind      *string
	PlayID    *string
	Data      *string
	ReadAt    *time.Time
	CreatedAt time.Time
}

type Venue struct {
	ID            int64
	PostalCode    *string
	Name          string
	Address       string
	Latitude      float64
	Longitude     float64
	Source        string
	SearchTerm    *string
	GooglePlaceID *string
}

type VenueAlias struct {
	Alias   string
	VenueID int64
}

type WebPushSubscription struct {
	Endpoint         string
	UserID           string
	Auth             string
	P256dh           string
	ExpirationTimeMs *int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type WebPushVapidKey struct {
	ID         int64
	PublicKey  string
	PrivateKey string
	CreatedAt  time.Time
	UpdatedAt  time.Time
}
