// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type RawMessage struct {
	ID             int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Source         string
	SenderUsername string
	MessageText    string
	MessageTime    time.Time
	ContentHash    string
	Status         string
	RetryCount     int64
	NextRetryAt    *time.Time
	LastError      *string
	LlmResponse    *string
}
