// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"strings"
)

const createUserNotification = `-- name: CreateUserNotification :one
INSERT INTO user_notifications (
    id,
    user_id,
    title,
    body,
    url,
    tag,
    kind,
    play_id,
    data
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, title, body, url, tag, kind, play_id, data, read_at, created_at
`

type CreateUserNotificationParams struct {
	ID     string
	UserID string
	Title  string
	Body   *string
	Url    *string
	Tag    *string
	Kind   *string
	PlayID *string
	Data   *string
}

func (q *Queries) CreateUserNotification(ctx context.Context, arg CreateUserNotificationParams) (UserNotification, error) {
	row := q.db.QueryRowContext(ctx, createUserNotification,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Body,
		arg.Url,
		arg.Tag,
		arg.Kind,
		arg.PlayID,
		arg.Data,
	)
	var i UserNotification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Body,
		&i.Url,
		&i.Tag,
		&i.Kind,
		&i.PlayID,
		&i.Data,
		&i.ReadAt,
		&i.CreatedAt,
	)
	return i, err
}

const createWebPushVAPIDKeys = `-- name: CreateWebPushVAPIDKeys :one
INSERT INTO web_push_vapid_keys (
    id,
    public_key,
    private_key
) VALUES (
    1, ?, ?
)
ON CONFLICT(id) DO UPDATE SET
    public_key = web_push_vapid_keys.public_key
RETURNING id, public_key, private_key, created_at, updated_at
`

type CreateWebPushVAPIDKeysParams struct {
	PublicKey  string
	PrivateKey string
}

// No-op update returns the existing singleton row during concurrent first boot.
func (q *Queries) CreateWebPushVAPIDKeys(ctx context.Context, arg CreateWebPushVAPIDKeysParams) (WebPushVapidKey, error) {
	row := q.db.QueryRowContext(ctx, createWebPushVAPIDKeys, arg.PublicKey, arg.PrivateKey)
	var i WebPushVapidKey
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebPushSubscription = `-- name: DeleteWebPushSubscription :exec
DELETE FROM web_push_subscriptions
WHERE user_id = ? AND endpoint = ?
`

type DeleteWebPushSubscriptionParams struct {
	UserID   string
	Endpoint string
}

func (q *Queries) DeleteWebPushSubscription(ctx context.Context, arg DeleteWebPushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, deleteWebPushSubscription, arg.UserID, arg.Endpoint)
	return err
}

const getWebPushVAPIDKeys = `-- name: GetWebPushVAPIDKeys :one
SELECT id, public_key, private_key, created_at, updated_at FROM web_push_vapid_keys
WHERE id = 1
`

func (q *Queries) GetWebPushVAPIDKeys(ctx context.Context) (WebPushVapidKey, error) {
	row := q.db.QueryRowContext(ctx, getWebPushVAPIDKeys)
	var i WebPushVapidKey
	err := row.Scan(
		&i.ID,
		&i.PublicKey,
		&i.PrivateKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUserNotifications = `-- name: ListUserNotifications :many
SELECT id, user_id, title, body, url, tag, kind, play_id, data, read_at, created_at FROM user_notifications
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
LIMIT ?
`

type ListUserNotificationsParams struct {
	UserID string
	Limit  int64
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]UserNotification, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotifications, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserNotification
	for rows.Next() {
		var i UserNotification
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Body,
			&i.Url,
			&i.Tag,
			&i.Kind,
			&i.PlayID,
			&i.Data,
			&i.ReadAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebPushSubscriptionsByUser = `-- name: ListWebPushSubscriptionsByUser :many
SELECT endpoint, user_id, auth, p256dh, expiration_time_ms, created_at, updated_at FROM web_push_subscriptions
WHERE user_id = ?
ORDER BY updated_at DESC, endpoint ASC
`

func (q *Queries) ListWebPushSubscriptionsByUser(ctx context.Context, userID string) ([]WebPushSubscription, error) {
	rows, err := q.db.QueryContext(ctx, listWebPushSubscriptionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WebPushSubscription
	for rows.Next() {
		var i WebPushSubscription
		if err := rows.Scan(
			&i.Endpoint,
			&i.UserID,
			&i.Auth,
			&i.P256dh,
			&i.ExpirationTimeMs,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllUserNotificationsRead = `-- name: MarkAllUserNotificationsRead :exec
UPDATE user_notifications
SET read_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE user_id = ? AND read_at IS NULL
`

func (q *Queries) MarkAllUserNotificationsRead(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, markAllUserNotificationsRead, userID)
	return err
}

const markUserNotificationsRead = `-- name: MarkUserNotificationsRead :exec
UPDATE user_notifications
SET read_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE user_id = ?
  AND id IN (/*SLICE:ids*/?)
  AND read_at IS NULL
`

type MarkUserNotificationsReadParams struct {
	UserID string
	Ids    []string
}

func (q *Queries) MarkUserNotificationsRead(ctx context.Context, arg MarkUserNotificationsReadParams) error {
	query := markUserNotificationsRead
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const upsertWebPushSubscription = `-- name: UpsertWebPushSubscription :exec
INSERT INTO web_push_subscriptions (
    endpoint,
    user_id,
    auth,
    p256dh,
    expiration_time_ms
) VALUES (
    ?, ?, ?, ?, ?
)
ON CONFLICT(endpoint) DO UPDATE SET
    user_id = excluded.user_id,
    auth = excluded.auth,
    p256dh = excluded.p256dh,
    expiration_time_ms = excluded.expiration_time_ms,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
`

type UpsertWebPushSubscriptionParams struct {
	Endpoint         string
	UserID           string
	Auth             string
	P256dh           string
	ExpirationTimeMs *int64
}

func (q *Queries) UpsertWebPushSubscription(ctx context.Context, arg UpsertWebPushSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, upsertWebPushSubscription,
		arg.Endpoint,
		arg.UserID,
		arg.Auth,
		arg.P256dh,
		arg.ExpirationTimeMs,
	)
	return err
}
