// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plays.sql

package db

import (
	"context"
	"time"

	"openplays/server/internal/model"
)

const cancelUserCreatedPlay = `-- name: CancelUserCreatedPlay :one
UPDATE plays
SET
    cancelled_at = COALESCE(cancelled_at, strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')),
    cancelled_by = COALESCE(cancelled_by, ?1),
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?2
  AND created_by IS NOT NULL
RETURNING id, created_at, updated_at, listing_type, sport, game_type, host_name, starts_at, ends_at, timezone, venue, level_min, level_max, level_min_ord, level_max_ord, fee, currency, max_players, slots_left, courts, contacts, gender_pref, meta, source, source_sender_username, source_raw_message, source_message_time, venue_id, source_message_id, source_group, source_sender_name, created_by, cancelled_at, cancelled_by, name, description, visibility, require_waitlist
`

type CancelUserCreatedPlayParams struct {
	CancelledBy *string
	ID          string
}

func (q *Queries) CancelUserCreatedPlay(ctx context.Context, arg CancelUserCreatedPlayParams) (Play, error) {
	row := q.db.QueryRowContext(ctx, cancelUserCreatedPlay, arg.CancelledBy, arg.ID)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListingType,
		&i.Sport,
		&i.GameType,
		&i.HostName,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Venue,
		&i.LevelMin,
		&i.LevelMax,
		&i.LevelMinOrd,
		&i.LevelMaxOrd,
		&i.Fee,
		&i.Currency,
		&i.MaxPlayers,
		&i.SlotsLeft,
		&i.Courts,
		&i.Contacts,
		&i.GenderPref,
		&i.Meta,
		&i.Source,
		&i.SourceSenderUsername,
		&i.SourceRawMessage,
		&i.SourceMessageTime,
		&i.VenueID,
		&i.SourceMessageID,
		&i.SourceGroup,
		&i.SourceSenderName,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.RequireWaitlist,
	)
	return i, err
}

const countMyUpcomingPlays = `-- name: CountMyUpcomingPlays :one
SELECT COUNT(*) FROM plays p
LEFT JOIN play_participants pp ON pp.play_id = p.id AND pp.user_id = ?1
WHERE p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.cancelled_at IS NULL
  AND (
    EXISTS (
        SELECT 1
        FROM play_hosts ph
        WHERE ph.play_id = p.id AND ph.user_id = ?1
    )
    OR p.created_by = ?1
    OR pp.id IS NOT NULL
  )
`

// Total count of upcoming listings where the current user is a host or participant.
func (q *Queries) CountMyUpcomingPlays(ctx context.Context, userID *string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMyUpcomingPlays, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUpcomingPlays = `-- name: CountUpcomingPlays :one
SELECT COUNT(*) FROM plays p
WHERE p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.cancelled_at IS NULL
  AND p.visibility = 'public'
  AND (?1 IS NULL OR p.starts_at >= ?1)
  AND (?2 IS NULL OR p.starts_at < ?2)
  AND (?3 IS NULL OR p.listing_type = ?3)
  AND (?4 IS NULL OR p.sport = ?4)
  AND (?5 IS NULL OR p.venue_id = ?5)
  AND (?6 IS NULL OR (p.level_max_ord IS NULL OR p.level_max_ord >= ?6))
  AND (?7 IS NULL OR (p.level_min_ord IS NULL OR p.level_min_ord <= ?7))
`

type CountUpcomingPlaysParams struct {
	StartsAfter       interface{}
	StartsBefore      interface{}
	ListingType       interface{}
	Sport             interface{}
	VenueID           interface{}
	FilterLevelMinOrd interface{}
	FilterLevelMaxOrd interface{}
}

// Total count of upcoming listings matching the same filters.
func (q *Queries) CountUpcomingPlays(ctx context.Context, arg CountUpcomingPlaysParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUpcomingPlays,
		arg.StartsAfter,
		arg.StartsBefore,
		arg.ListingType,
		arg.Sport,
		arg.VenueID,
		arg.FilterLevelMinOrd,
		arg.FilterLevelMaxOrd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUpcomingPlaysByDistance = `-- name: CountUpcomingPlaysByDistance :one
SELECT COUNT(*) FROM plays p
INNER JOIN venues v ON v.id = p.venue_id
WHERE p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.cancelled_at IS NULL
  AND p.visibility = 'public'
  AND (?1 IS NULL OR p.starts_at >= ?1)
  AND (?2 IS NULL OR p.starts_at < ?2)
  AND (?3 IS NULL OR p.listing_type = ?3)
  AND (?4 IS NULL OR p.sport = ?4)
  AND (?5 IS NULL OR p.venue_id = ?5)
  AND (?6 IS NULL OR (p.level_max_ord IS NULL OR p.level_max_ord >= ?6))
  AND (?7 IS NULL OR (p.level_min_ord IS NULL OR p.level_min_ord <= ?7))
`

type CountUpcomingPlaysByDistanceParams struct {
	StartsAfter       interface{}
	StartsBefore      interface{}
	ListingType       interface{}
	Sport             interface{}
	VenueID           interface{}
	FilterLevelMinOrd interface{}
	FilterLevelMaxOrd interface{}
}

// Total count of upcoming listings with a resolved venue, matching the same filters.
func (q *Queries) CountUpcomingPlaysByDistance(ctx context.Context, arg CountUpcomingPlaysByDistanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUpcomingPlaysByDistance,
		arg.StartsAfter,
		arg.StartsBefore,
		arg.ListingType,
		arg.Sport,
		arg.VenueID,
		arg.FilterLevelMinOrd,
		arg.FilterLevelMaxOrd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlay = `-- name: CreatePlay :one
INSERT INTO plays (
    id, listing_type, sport, game_type, host_name, name, description,
    starts_at, ends_at, timezone,
    venue, venue_id,
    level_min, level_max, level_min_ord, level_max_ord,
    fee, currency, max_players, slots_left, courts,
    contacts, gender_pref, meta,
    source, created_by, visibility, require_waitlist
) VALUES (
    ?, ?, ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    'user', ?, COALESCE(NULLIF(?26, ''), 'public'), ?27
)
RETURNING id, created_at, updated_at, listing_type, sport, game_type, host_name, starts_at, ends_at, timezone, venue, level_min, level_max, level_min_ord, level_max_ord, fee, currency, max_players, slots_left, courts, contacts, gender_pref, meta, source, source_sender_username, source_raw_message, source_message_time, venue_id, source_message_id, source_group, source_sender_name, created_by, cancelled_at, cancelled_by, name, description, visibility, require_waitlist
`

type CreatePlayParams struct {
	ID              string
	ListingType     model.ListingType
	Sport           model.Sport
	GameType        *model.GameType
	HostName        string
	Name            *string
	Description     *string
	StartsAt        time.Time
	EndsAt          time.Time
	Timezone        string
	Venue           string
	VenueID         *int64
	LevelMin        *string
	LevelMax        *string
	LevelMinOrd     *int64
	LevelMaxOrd     *int64
	Fee             *int64
	Currency        string
	MaxPlayers      *int64
	SlotsLeft       *int64
	Courts          *int64
	Contacts        model.Contacts
	GenderPref      *model.GenderPref
	Meta            model.Meta
	CreatedBy       *string
	Visibility      interface{}
	RequireWaitlist bool
}

func (q *Queries) CreatePlay(ctx context.Context, arg CreatePlayParams) (Play, error) {
	row := q.db.QueryRowContext(ctx, createPlay,
		arg.ID,
		arg.ListingType,
		arg.Sport,
		arg.GameType,
		arg.HostName,
		arg.Name,
		arg.Description,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.Venue,
		arg.VenueID,
		arg.LevelMin,
		arg.LevelMax,
		arg.LevelMinOrd,
		arg.LevelMaxOrd,
		arg.Fee,
		arg.Currency,
		arg.MaxPlayers,
		arg.SlotsLeft,
		arg.Courts,
		arg.Contacts,
		arg.GenderPref,
		arg.Meta,
		arg.CreatedBy,
		arg.Visibility,
		arg.RequireWaitlist,
	)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListingType,
		&i.Sport,
		&i.GameType,
		&i.HostName,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Venue,
		&i.LevelMin,
		&i.LevelMax,
		&i.LevelMinOrd,
		&i.LevelMaxOrd,
		&i.Fee,
		&i.Currency,
		&i.MaxPlayers,
		&i.SlotsLeft,
		&i.Courts,
		&i.Contacts,
		&i.GenderPref,
		&i.Meta,
		&i.Source,
		&i.SourceSenderUsername,
		&i.SourceRawMessage,
		&i.SourceMessageTime,
		&i.VenueID,
		&i.SourceMessageID,
		&i.SourceGroup,
		&i.SourceSenderName,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.RequireWaitlist,
	)
	return i, err
}

const getPlayByID = `-- name: GetPlayByID :one
SELECT
    p.id, p.created_at, p.updated_at,
    p.listing_type, p.sport, p.game_type, p.host_name, p.name, p.description, p.visibility, p.require_waitlist,
    p.starts_at, p.ends_at, p.timezone,
    p.venue, p.venue_id, p.created_by, p.cancelled_at, p.cancelled_by,
    p.level_min, p.level_max, p.level_min_ord, p.level_max_ord,
    p.fee, p.currency, p.max_players, p.slots_left, p.courts,
    p.contacts, p.gender_pref, p.meta,
    p.source, p.source_sender_username, p.source_message_id, p.source_group,
    COALESCE(v.name, NULLIF(p.venue, ''), 'No venue') AS venue_name, v.postal_code AS venue_postal_code,
    v.latitude AS venue_latitude, v.longitude AS venue_longitude, v.google_place_id AS venue_google_place_id,
    u.display_name AS creator_display_name, u.username AS creator_username, u.photo_url AS creator_photo_url
FROM plays p
LEFT JOIN venues v ON v.id = p.venue_id
LEFT JOIN users u ON u.id = p.created_by
WHERE p.id = ?
`

type GetPlayByIDRow struct {
	ID                   string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ListingType          model.ListingType
	Sport                model.Sport
	GameType             *model.GameType
	HostName             string
	Name                 *string
	Description          *string
	Visibility           model.PlayVisibility
	RequireWaitlist      bool
	StartsAt             time.Time
	EndsAt               time.Time
	Timezone             string
	Venue                string
	VenueID              *int64
	CreatedBy            *string
	CancelledAt          *time.Time
	CancelledBy          *string
	LevelMin             *string
	LevelMax             *string
	LevelMinOrd          *int64
	LevelMaxOrd          *int64
	Fee                  *int64
	Currency             string
	MaxPlayers           *int64
	SlotsLeft            *int64
	Courts               *int64
	Contacts             model.Contacts
	GenderPref           *model.GenderPref
	Meta                 model.Meta
	Source               *string
	SourceSenderUsername *string
	SourceMessageID      *string
	SourceGroup          *string
	VenueName            string
	VenuePostalCode      *string
	VenueLatitude        *float64
	VenueLongitude       *float64
	VenueGooglePlaceID   *string
	CreatorDisplayName   *string
	CreatorUsername      *string
	CreatorPhotoUrl      *string
}

func (q *Queries) GetPlayByID(ctx context.Context, id string) (GetPlayByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPlayByID, id)
	var i GetPlayByIDRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListingType,
		&i.Sport,
		&i.GameType,
		&i.HostName,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.RequireWaitlist,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Venue,
		&i.VenueID,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.LevelMin,
		&i.LevelMax,
		&i.LevelMinOrd,
		&i.LevelMaxOrd,
		&i.Fee,
		&i.Currency,
		&i.MaxPlayers,
		&i.SlotsLeft,
		&i.Courts,
		&i.Contacts,
		&i.GenderPref,
		&i.Meta,
		&i.Source,
		&i.SourceSenderUsername,
		&i.SourceMessageID,
		&i.SourceGroup,
		&i.VenueName,
		&i.VenuePostalCode,
		&i.VenueLatitude,
		&i.VenueLongitude,
		&i.VenueGooglePlaceID,
		&i.CreatorDisplayName,
		&i.CreatorUsername,
		&i.CreatorPhotoUrl,
	)
	return i, err
}

const getUpcomingPlays = `-- name: GetUpcomingPlays :many
SELECT id, created_at, updated_at, listing_type, sport, game_type, host_name, starts_at, ends_at, timezone, venue, level_min, level_max, level_min_ord, level_max_ord, fee, currency, max_players, slots_left, courts, contacts, gender_pref, meta, source, source_sender_username, source_raw_message, source_message_time, venue_id, source_message_id, source_group, source_sender_name, created_by, cancelled_at, cancelled_by, name, description, visibility, require_waitlist FROM plays
WHERE ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND cancelled_at IS NULL
  AND visibility = 'public'
  AND listing_type = 'play'
ORDER BY starts_at ASC
`

func (q *Queries) GetUpcomingPlays(ctx context.Context) ([]Play, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingPlays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListingType,
			&i.Sport,
			&i.GameType,
			&i.HostName,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.Venue,
			&i.LevelMin,
			&i.LevelMax,
			&i.LevelMinOrd,
			&i.LevelMaxOrd,
			&i.Fee,
			&i.Currency,
			&i.MaxPlayers,
			&i.SlotsLeft,
			&i.Courts,
			&i.Contacts,
			&i.GenderPref,
			&i.Meta,
			&i.Source,
			&i.SourceSenderUsername,
			&i.SourceRawMessage,
			&i.SourceMessageTime,
			&i.VenueID,
			&i.SourceMessageID,
			&i.SourceGroup,
			&i.SourceSenderName,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.CancelledBy,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.RequireWaitlist,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyUpcomingPlays = `-- name: ListMyUpcomingPlays :many
SELECT
    p.id, p.created_at, p.updated_at,
    p.listing_type, p.sport, p.game_type, p.host_name, p.name, p.description, p.visibility, p.require_waitlist,
    p.starts_at, p.ends_at, p.timezone,
    p.venue, p.venue_id, p.created_by, p.cancelled_at,
    p.level_min, p.level_max, p.level_min_ord, p.level_max_ord,
    p.fee, p.currency, p.max_players, p.slots_left, p.courts,
    p.contacts, p.gender_pref, p.meta,
    p.source, p.source_sender_username, p.source_message_id, p.source_group,
    COALESCE(v.name, NULLIF(p.venue, ''), 'No venue') AS venue_name, v.postal_code AS venue_postal_code,
    v.latitude AS venue_latitude, v.longitude AS venue_longitude, v.google_place_id AS venue_google_place_id,
    u.display_name AS creator_display_name, u.username AS creator_username, u.photo_url AS creator_photo_url,
    CAST(CASE
        WHEN EXISTS (
            SELECT 1
            FROM play_hosts ph
            WHERE ph.play_id = p.id AND ph.user_id = ?1
        ) OR p.created_by = ?1 THEN 'creator'
        WHEN pp.status = 'confirmed' THEN 'confirmed'
        WHEN pp.status = 'added' THEN 'added'
        WHEN pp.status = 'waitlisted' THEN 'waitlisted'
        ELSE pp.status
    END AS TEXT) AS viewer_state
FROM plays p
LEFT JOIN play_participants pp ON pp.play_id = p.id AND pp.user_id = ?1
LEFT JOIN venues v ON v.id = p.venue_id
LEFT JOIN users u ON u.id = p.created_by
WHERE p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.cancelled_at IS NULL
  AND (
    EXISTS (
        SELECT 1
        FROM play_hosts ph
        WHERE ph.play_id = p.id AND ph.user_id = ?1
    )
    OR p.created_by = ?1
    OR pp.id IS NOT NULL
  )
  AND (?2 IS NULL
    OR p.starts_at > ?2
    OR (p.starts_at = ?2 AND p.id > ?3))
ORDER BY p.starts_at ASC, p.id ASC
LIMIT ?4
`

type ListMyUpcomingPlaysParams struct {
	UserID         string
	CursorStartsAt interface{}
	CursorID       *string
	PageSize       int64
}

type ListMyUpcomingPlaysRow struct {
	ID                   string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ListingType          model.ListingType
	Sport                model.Sport
	GameType             *model.GameType
	HostName             string
	Name                 *string
	Description          *string
	Visibility           model.PlayVisibility
	RequireWaitlist      bool
	StartsAt             time.Time
	EndsAt               time.Time
	Timezone             string
	Venue                string
	VenueID              *int64
	CreatedBy            *string
	CancelledAt          *time.Time
	LevelMin             *string
	LevelMax             *string
	LevelMinOrd          *int64
	LevelMaxOrd          *int64
	Fee                  *int64
	Currency             string
	MaxPlayers           *int64
	SlotsLeft            *int64
	Courts               *int64
	Contacts             model.Contacts
	GenderPref           *model.GenderPref
	Meta                 model.Meta
	Source               *string
	SourceSenderUsername *string
	SourceMessageID      *string
	SourceGroup          *string
	VenueName            string
	VenuePostalCode      *string
	VenueLatitude        *float64
	VenueLongitude       *float64
	VenueGooglePlaceID   *string
	CreatorDisplayName   *string
	CreatorUsername      *string
	CreatorPhotoUrl      *string
	ViewerState          string
}

// Paginated upcoming listings where the current user is a host or participant.
// Host relationship comes from play_hosts; created_by is a transitional fallback.
// TODO: Audit remaining created_by usage and drop plays.created_by if play_hosts fully replaces it.
func (q *Queries) ListMyUpcomingPlays(ctx context.Context, arg ListMyUpcomingPlaysParams) ([]ListMyUpcomingPlaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listMyUpcomingPlays,
		arg.UserID,
		arg.CursorStartsAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyUpcomingPlaysRow
	for rows.Next() {
		var i ListMyUpcomingPlaysRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListingType,
			&i.Sport,
			&i.GameType,
			&i.HostName,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.RequireWaitlist,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.Venue,
			&i.VenueID,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.LevelMin,
			&i.LevelMax,
			&i.LevelMinOrd,
			&i.LevelMaxOrd,
			&i.Fee,
			&i.Currency,
			&i.MaxPlayers,
			&i.SlotsLeft,
			&i.Courts,
			&i.Contacts,
			&i.GenderPref,
			&i.Meta,
			&i.Source,
			&i.SourceSenderUsername,
			&i.SourceMessageID,
			&i.SourceGroup,
			&i.VenueName,
			&i.VenuePostalCode,
			&i.VenueLatitude,
			&i.VenueLongitude,
			&i.VenueGooglePlaceID,
			&i.CreatorDisplayName,
			&i.CreatorUsername,
			&i.CreatorPhotoUrl,
			&i.ViewerState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingPlays = `-- name: ListUpcomingPlays :many
SELECT
    p.id, p.created_at, p.updated_at,
    p.listing_type, p.sport, p.game_type, p.host_name, p.name, p.description, p.visibility, p.require_waitlist,
    p.starts_at, p.ends_at, p.timezone,
    p.venue, p.venue_id, p.created_by, p.cancelled_at,
    p.level_min, p.level_max, p.level_min_ord, p.level_max_ord,
    p.fee, p.currency, p.max_players, p.slots_left, p.courts,
    p.contacts, p.gender_pref, p.meta,
    p.source, p.source_sender_username, p.source_message_id, p.source_group,
    COALESCE(v.name, NULLIF(p.venue, ''), 'No venue') AS venue_name, v.postal_code AS venue_postal_code,
    v.latitude AS venue_latitude, v.longitude AS venue_longitude, v.google_place_id AS venue_google_place_id,
    u.display_name AS creator_display_name, u.username AS creator_username, u.photo_url AS creator_photo_url
FROM plays p
LEFT JOIN venues v ON v.id = p.venue_id
LEFT JOIN users u ON u.id = p.created_by
WHERE p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.cancelled_at IS NULL
  AND p.visibility = 'public'
  AND (?1 IS NULL OR p.starts_at >= ?1)
  AND (?2 IS NULL OR p.starts_at < ?2)
  AND (?3 IS NULL OR p.listing_type = ?3)
  AND (?4 IS NULL OR p.sport = ?4)
  AND (?5 IS NULL OR p.venue_id = ?5)
  AND (?6 IS NULL OR (p.level_max_ord IS NULL OR p.level_max_ord >= ?6))
  AND (?7 IS NULL OR (p.level_min_ord IS NULL OR p.level_min_ord <= ?7))
  AND (?8 IS NULL
    OR p.starts_at > ?8
    OR (p.starts_at = ?8 AND p.id > ?9))
ORDER BY p.starts_at ASC, p.id ASC
LIMIT ?10
`

type ListUpcomingPlaysParams struct {
	StartsAfter       interface{}
	StartsBefore      interface{}
	ListingType       interface{}
	Sport             interface{}
	VenueID           interface{}
	FilterLevelMinOrd interface{}
	FilterLevelMaxOrd interface{}
	CursorStartsAt    interface{}
	CursorID          *string
	PageSize          int64
}

type ListUpcomingPlaysRow struct {
	ID                   string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ListingType          model.ListingType
	Sport                model.Sport
	GameType             *model.GameType
	HostName             string
	Name                 *string
	Description          *string
	Visibility           model.PlayVisibility
	RequireWaitlist      bool
	StartsAt             time.Time
	EndsAt               time.Time
	Timezone             string
	Venue                string
	VenueID              *int64
	CreatedBy            *string
	CancelledAt          *time.Time
	LevelMin             *string
	LevelMax             *string
	LevelMinOrd          *int64
	LevelMaxOrd          *int64
	Fee                  *int64
	Currency             string
	MaxPlayers           *int64
	SlotsLeft            *int64
	Courts               *int64
	Contacts             model.Contacts
	GenderPref           *model.GenderPref
	Meta                 model.Meta
	Source               *string
	SourceSenderUsername *string
	SourceMessageID      *string
	SourceGroup          *string
	VenueName            string
	VenuePostalCode      *string
	VenueLatitude        *float64
	VenueLongitude       *float64
	VenueGooglePlaceID   *string
	CreatorDisplayName   *string
	CreatorUsername      *string
	CreatorPhotoUrl      *string
}

// Paginated upcoming listings with optional filters and venue data.
// Includes games still in progress (ends_at > now) not just future games.
// Forward-only cursor pagination using composite (starts_at, id) cursor
// to match the sort order. Both cursor params must be provided together.
func (q *Queries) ListUpcomingPlays(ctx context.Context, arg ListUpcomingPlaysParams) ([]ListUpcomingPlaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingPlays,
		arg.StartsAfter,
		arg.StartsBefore,
		arg.ListingType,
		arg.Sport,
		arg.VenueID,
		arg.FilterLevelMinOrd,
		arg.FilterLevelMaxOrd,
		arg.CursorStartsAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingPlaysRow
	for rows.Next() {
		var i ListUpcomingPlaysRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListingType,
			&i.Sport,
			&i.GameType,
			&i.HostName,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.RequireWaitlist,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.Venue,
			&i.VenueID,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.LevelMin,
			&i.LevelMax,
			&i.LevelMinOrd,
			&i.LevelMaxOrd,
			&i.Fee,
			&i.Currency,
			&i.MaxPlayers,
			&i.SlotsLeft,
			&i.Courts,
			&i.Contacts,
			&i.GenderPref,
			&i.Meta,
			&i.Source,
			&i.SourceSenderUsername,
			&i.SourceMessageID,
			&i.SourceGroup,
			&i.VenueName,
			&i.VenuePostalCode,
			&i.VenueLatitude,
			&i.VenueLongitude,
			&i.VenueGooglePlaceID,
			&i.CreatorDisplayName,
			&i.CreatorUsername,
			&i.CreatorPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUpcomingPlaysByDistance = `-- name: ListUpcomingPlaysByDistance :many
SELECT
    p.id, p.created_at, p.updated_at,
    p.listing_type, p.sport, p.game_type, p.host_name, p.name, p.description, p.visibility, p.require_waitlist,
    p.starts_at, p.ends_at, p.timezone,
    p.venue, p.venue_id, p.created_by, p.cancelled_at,
    p.level_min, p.level_max, p.level_min_ord, p.level_max_ord,
    p.fee, p.currency, p.max_players, p.slots_left, p.courts,
    p.contacts, p.gender_pref, p.meta,
    p.source, p.source_sender_username, p.source_message_id, p.source_group,
    COALESCE(v.name, NULLIF(p.venue, ''), 'No venue') AS venue_name, v.postal_code AS venue_postal_code,
    v.latitude AS venue_latitude, v.longitude AS venue_longitude, v.google_place_id AS venue_google_place_id,
    u.display_name AS creator_display_name, u.username AS creator_username, u.photo_url AS creator_photo_url,
    CAST(2 * 6371 * asin(sqrt(
        pow(sin((radians(v.latitude) - radians(?1)) / 2), 2) +
        cos(radians(?1)) * cos(radians(v.latitude)) *
        pow(sin((radians(v.longitude) - radians(?2)) / 2), 2)
    )) AS REAL) AS distance_km
FROM plays p
INNER JOIN venues v ON v.id = p.venue_id
LEFT JOIN users u ON u.id = p.created_by
WHERE p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.cancelled_at IS NULL
  AND p.visibility = 'public'
  AND (?3 IS NULL OR p.starts_at >= ?3)
  AND (?4 IS NULL OR p.starts_at < ?4)
  AND (?5 IS NULL OR p.listing_type = ?5)
  AND (?6 IS NULL OR p.sport = ?6)
  AND (?7 IS NULL OR p.venue_id = ?7)
  AND (?8 IS NULL OR (p.level_max_ord IS NULL OR p.level_max_ord >= ?8))
  AND (?9 IS NULL OR (p.level_min_ord IS NULL OR p.level_min_ord <= ?9))
  AND (?10 IS NULL
    OR 2 * 6371 * asin(sqrt(
        pow(sin((radians(v.latitude) - radians(?1)) / 2), 2) +
        cos(radians(?1)) * cos(radians(v.latitude)) *
        pow(sin((radians(v.longitude) - radians(?2)) / 2), 2)
    )) > ?10
    OR (2 * 6371 * asin(sqrt(
        pow(sin((radians(v.latitude) - radians(?1)) / 2), 2) +
        cos(radians(?1)) * cos(radians(v.latitude)) *
        pow(sin((radians(v.longitude) - radians(?2)) / 2), 2)
    )) = ?10 AND p.id > ?11))
ORDER BY distance_km ASC, p.id ASC
LIMIT ?12
`

type ListUpcomingPlaysByDistanceParams struct {
	RefLat            interface{}
	RefLng            interface{}
	StartsAfter       interface{}
	StartsBefore      interface{}
	ListingType       interface{}
	Sport             interface{}
	VenueID           interface{}
	FilterLevelMinOrd interface{}
	FilterLevelMaxOrd interface{}
	CursorDistance    interface{}
	CursorID          *string
	PageSize          int64
}

type ListUpcomingPlaysByDistanceRow struct {
	ID                   string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ListingType          model.ListingType
	Sport                model.Sport
	GameType             *model.GameType
	HostName             string
	Name                 *string
	Description          *string
	Visibility           model.PlayVisibility
	RequireWaitlist      bool
	StartsAt             time.Time
	EndsAt               time.Time
	Timezone             string
	Venue                string
	VenueID              *int64
	CreatedBy            *string
	CancelledAt          *time.Time
	LevelMin             *string
	LevelMax             *string
	LevelMinOrd          *int64
	LevelMaxOrd          *int64
	Fee                  *int64
	Currency             string
	MaxPlayers           *int64
	SlotsLeft            *int64
	Courts               *int64
	Contacts             model.Contacts
	GenderPref           *model.GenderPref
	Meta                 model.Meta
	Source               *string
	SourceSenderUsername *string
	SourceMessageID      *string
	SourceGroup          *string
	VenueName            string
	VenuePostalCode      *string
	VenueLatitude        float64
	VenueLongitude       float64
	VenueGooglePlaceID   *string
	CreatorDisplayName   *string
	CreatorUsername      *string
	CreatorPhotoUrl      *string
	DistanceKm           float64
}

// Paginated upcoming listings sorted by Haversine distance from a reference point.
// Only includes plays with a resolved venue (INNER JOIN).
// Forward-only cursor pagination using composite (distance_km, id).
func (q *Queries) ListUpcomingPlaysByDistance(ctx context.Context, arg ListUpcomingPlaysByDistanceParams) ([]ListUpcomingPlaysByDistanceRow, error) {
	rows, err := q.db.QueryContext(ctx, listUpcomingPlaysByDistance,
		arg.RefLat,
		arg.RefLng,
		arg.StartsAfter,
		arg.StartsBefore,
		arg.ListingType,
		arg.Sport,
		arg.VenueID,
		arg.FilterLevelMinOrd,
		arg.FilterLevelMaxOrd,
		arg.CursorDistance,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUpcomingPlaysByDistanceRow
	for rows.Next() {
		var i ListUpcomingPlaysByDistanceRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListingType,
			&i.Sport,
			&i.GameType,
			&i.HostName,
			&i.Name,
			&i.Description,
			&i.Visibility,
			&i.RequireWaitlist,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.Venue,
			&i.VenueID,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.LevelMin,
			&i.LevelMax,
			&i.LevelMinOrd,
			&i.LevelMaxOrd,
			&i.Fee,
			&i.Currency,
			&i.MaxPlayers,
			&i.SlotsLeft,
			&i.Courts,
			&i.Contacts,
			&i.GenderPref,
			&i.Meta,
			&i.Source,
			&i.SourceSenderUsername,
			&i.SourceMessageID,
			&i.SourceGroup,
			&i.VenueName,
			&i.VenuePostalCode,
			&i.VenueLatitude,
			&i.VenueLongitude,
			&i.VenueGooglePlaceID,
			&i.CreatorDisplayName,
			&i.CreatorUsername,
			&i.CreatorPhotoUrl,
			&i.DistanceKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlaySlotsLeft = `-- name: UpdatePlaySlotsLeft :exec
UPDATE plays
SET
    slots_left = CASE
        WHEN max_players IS NULL THEN NULL
        ELSE max(max_players - (
            SELECT COUNT(*)
            FROM play_participants pp
            WHERE pp.play_id = plays.id
              AND pp.status IN ('confirmed', 'added')
        ), 0)
    END,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE plays.id = ?
`

func (q *Queries) UpdatePlaySlotsLeft(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updatePlaySlotsLeft, id)
	return err
}

const updateUserCreatedPlay = `-- name: UpdateUserCreatedPlay :one
UPDATE plays
SET
    name = ?1,
    description = ?2,
    visibility = COALESCE(NULLIF(?3, ''), visibility),
    require_waitlist = ?4,
    game_type = ?5,
    starts_at = ?6,
    ends_at = ?7,
    timezone = ?8,
    level_min = ?9,
    level_max = ?10,
    level_min_ord = ?11,
    level_max_ord = ?12,
    fee = ?13,
    max_players = ?14,
    slots_left = CASE
        WHEN ?14 IS NULL THEN NULL
        ELSE max(?14 - (
            SELECT COUNT(*)
            FROM play_participants pp
            WHERE pp.play_id = plays.id
              AND pp.status IN ('confirmed', 'added')
        ), 0)
    END,
    courts = ?15,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE plays.id = ?16
  AND plays.created_by IS NOT NULL
RETURNING id, created_at, updated_at, listing_type, sport, game_type, host_name, starts_at, ends_at, timezone, venue, level_min, level_max, level_min_ord, level_max_ord, fee, currency, max_players, slots_left, courts, contacts, gender_pref, meta, source, source_sender_username, source_raw_message, source_message_time, venue_id, source_message_id, source_group, source_sender_name, created_by, cancelled_at, cancelled_by, name, description, visibility, require_waitlist
`

type UpdateUserCreatedPlayParams struct {
	Name            *string
	Description     *string
	Visibility      interface{}
	RequireWaitlist bool
	GameType        *model.GameType
	StartsAt        time.Time
	EndsAt          time.Time
	Timezone        string
	LevelMin        *string
	LevelMax        *string
	LevelMinOrd     *int64
	LevelMaxOrd     *int64
	Fee             *int64
	MaxPlayers      *int64
	Courts          *int64
	ID              string
}

func (q *Queries) UpdateUserCreatedPlay(ctx context.Context, arg UpdateUserCreatedPlayParams) (Play, error) {
	row := q.db.QueryRowContext(ctx, updateUserCreatedPlay,
		arg.Name,
		arg.Description,
		arg.Visibility,
		arg.RequireWaitlist,
		arg.GameType,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.LevelMin,
		arg.LevelMax,
		arg.LevelMinOrd,
		arg.LevelMaxOrd,
		arg.Fee,
		arg.MaxPlayers,
		arg.Courts,
		arg.ID,
	)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListingType,
		&i.Sport,
		&i.GameType,
		&i.HostName,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Venue,
		&i.LevelMin,
		&i.LevelMax,
		&i.LevelMinOrd,
		&i.LevelMaxOrd,
		&i.Fee,
		&i.Currency,
		&i.MaxPlayers,
		&i.SlotsLeft,
		&i.Courts,
		&i.Contacts,
		&i.GenderPref,
		&i.Meta,
		&i.Source,
		&i.SourceSenderUsername,
		&i.SourceRawMessage,
		&i.SourceMessageTime,
		&i.VenueID,
		&i.SourceMessageID,
		&i.SourceGroup,
		&i.SourceSenderName,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.RequireWaitlist,
	)
	return i, err
}

const upsertPlay = `-- name: UpsertPlay :one
INSERT INTO plays (
    id, listing_type, sport, game_type, host_name,
    starts_at, ends_at, timezone,
    venue, venue_id,
    level_min, level_max, level_min_ord, level_max_ord,
    fee, currency, max_players, slots_left, courts,
    contacts, gender_pref, meta,
    source, source_sender_username, source_sender_name, source_raw_message, source_message_time,
    source_message_id, source_group
) VALUES (
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?
)
ON CONFLICT(host_name, starts_at, sport, COALESCE(venue_id, 0)) DO UPDATE SET
    listing_type          = excluded.listing_type,
    game_type             = excluded.game_type,
    ends_at               = excluded.ends_at,
    venue_id              = excluded.venue_id,
    level_min             = excluded.level_min,
    level_max             = excluded.level_max,
    level_min_ord         = excluded.level_min_ord,
    level_max_ord         = excluded.level_max_ord,
    fee                   = excluded.fee,
    currency              = excluded.currency,
    max_players           = excluded.max_players,
    slots_left            = excluded.slots_left,
    courts                = excluded.courts,
    contacts              = excluded.contacts,
    gender_pref           = excluded.gender_pref,
    meta                  = excluded.meta,
    source_sender_username = excluded.source_sender_username,
    source_sender_name    = excluded.source_sender_name,
    source_raw_message    = excluded.source_raw_message,
    source_message_time   = excluded.source_message_time,
    source_message_id     = excluded.source_message_id,
    source_group          = excluded.source_group,
    updated_at            = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
RETURNING id, created_at, updated_at, listing_type, sport, game_type, host_name, starts_at, ends_at, timezone, venue, level_min, level_max, level_min_ord, level_max_ord, fee, currency, max_players, slots_left, courts, contacts, gender_pref, meta, source, source_sender_username, source_raw_message, source_message_time, venue_id, source_message_id, source_group, source_sender_name, created_by, cancelled_at, cancelled_by, name, description, visibility, require_waitlist
`

type UpsertPlayParams struct {
	ID                   string
	ListingType          model.ListingType
	Sport                model.Sport
	GameType             *model.GameType
	HostName             string
	StartsAt             time.Time
	EndsAt               time.Time
	Timezone             string
	Venue                string
	VenueID              *int64
	LevelMin             *string
	LevelMax             *string
	LevelMinOrd          *int64
	LevelMaxOrd          *int64
	Fee                  *int64
	Currency             string
	MaxPlayers           *int64
	SlotsLeft            *int64
	Courts               *int64
	Contacts             model.Contacts
	GenderPref           *model.GenderPref
	Meta                 model.Meta
	Source               *string
	SourceSenderUsername *string
	SourceSenderName     *string
	SourceRawMessage     *string
	SourceMessageTime    *time.Time
	SourceMessageID      *string
	SourceGroup          *string
}

func (q *Queries) UpsertPlay(ctx context.Context, arg UpsertPlayParams) (Play, error) {
	row := q.db.QueryRowContext(ctx, upsertPlay,
		arg.ID,
		arg.ListingType,
		arg.Sport,
		arg.GameType,
		arg.HostName,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.Venue,
		arg.VenueID,
		arg.LevelMin,
		arg.LevelMax,
		arg.LevelMinOrd,
		arg.LevelMaxOrd,
		arg.Fee,
		arg.Currency,
		arg.MaxPlayers,
		arg.SlotsLeft,
		arg.Courts,
		arg.Contacts,
		arg.GenderPref,
		arg.Meta,
		arg.Source,
		arg.SourceSenderUsername,
		arg.SourceSenderName,
		arg.SourceRawMessage,
		arg.SourceMessageTime,
		arg.SourceMessageID,
		arg.SourceGroup,
	)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListingType,
		&i.Sport,
		&i.GameType,
		&i.HostName,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Venue,
		&i.LevelMin,
		&i.LevelMax,
		&i.LevelMinOrd,
		&i.LevelMaxOrd,
		&i.Fee,
		&i.Currency,
		&i.MaxPlayers,
		&i.SlotsLeft,
		&i.Courts,
		&i.Contacts,
		&i.GenderPref,
		&i.Meta,
		&i.Source,
		&i.SourceSenderUsername,
		&i.SourceRawMessage,
		&i.SourceMessageTime,
		&i.VenueID,
		&i.SourceMessageID,
		&i.SourceGroup,
		&i.SourceSenderName,
		&i.CreatedBy,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.Name,
		&i.Description,
		&i.Visibility,
		&i.RequireWaitlist,
	)
	return i, err
}
