// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_participants.sql

package db

import (
	"context"
	"strings"

	"openplays/server/internal/model"
)

const countConfirmedPlayParticipants = `-- name: CountConfirmedPlayParticipants :one
SELECT COUNT(*) FROM play_participants
WHERE play_id = ? AND status = 'confirmed'
`

func (q *Queries) CountConfirmedPlayParticipants(ctx context.Context, playID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfirmedPlayParticipants, playID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayParticipantsByStatus = `-- name: CountPlayParticipantsByStatus :one
SELECT COUNT(*) FROM play_participants
WHERE play_id = ? AND status = ?
`

type CountPlayParticipantsByStatusParams struct {
	PlayID string
	Status model.PlayParticipantStatus
}

func (q *Queries) CountPlayParticipantsByStatus(ctx context.Context, arg CountPlayParticipantsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayParticipantsByStatus, arg.PlayID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlayParticipant = `-- name: CreatePlayParticipant :one
INSERT INTO play_participants (
    play_id, user_id, guest_name, rating_code, rating_ord, status
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at
`

type CreatePlayParticipantParams struct {
	PlayID     string
	UserID     *string
	GuestName  *string
	RatingCode *string
	RatingOrd  *int64
	Status     model.PlayParticipantStatus
}

func (q *Queries) CreatePlayParticipant(ctx context.Context, arg CreatePlayParticipantParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, createPlayParticipant,
		arg.PlayID,
		arg.UserID,
		arg.GuestName,
		arg.RatingCode,
		arg.RatingOrd,
		arg.Status,
	)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayParticipant = `-- name: DeletePlayParticipant :exec
DELETE FROM play_participants
WHERE id = ?
`

func (q *Queries) DeletePlayParticipant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayParticipant, id)
	return err
}

const deletePlayParticipantByPlayAndUser = `-- name: DeletePlayParticipantByPlayAndUser :exec
DELETE FROM play_participants
WHERE play_id = ? AND user_id = ?
`

type DeletePlayParticipantByPlayAndUserParams struct {
	PlayID string
	UserID *string
}

func (q *Queries) DeletePlayParticipantByPlayAndUser(ctx context.Context, arg DeletePlayParticipantByPlayAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deletePlayParticipantByPlayAndUser, arg.PlayID, arg.UserID)
	return err
}

const getPlayParticipantByID = `-- name: GetPlayParticipantByID :one
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE id = ?
`

func (q *Queries) GetPlayParticipantByID(ctx context.Context, id int64) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, getPlayParticipantByID, id)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayParticipantByPlayAndUser = `-- name: GetPlayParticipantByPlayAndUser :one
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ? AND user_id = ?
`

type GetPlayParticipantByPlayAndUserParams struct {
	PlayID string
	UserID *string
}

func (q *Queries) GetPlayParticipantByPlayAndUser(ctx context.Context, arg GetPlayParticipantByPlayAndUserParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, getPlayParticipantByPlayAndUser, arg.PlayID, arg.UserID)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfirmedParticipantPreviewsByPlay = `-- name: ListConfirmedParticipantPreviewsByPlay :many
SELECT
    pp.id,
    pp.play_id,
    pp.user_id,
    pp.guest_name,
    pp.rating_code,
    u.display_name,
    u.photo_url,
    u.sports_profile
FROM play_participants pp
LEFT JOIN users u ON u.id = pp.user_id
WHERE pp.play_id = ? AND pp.status = 'confirmed'
ORDER BY pp.created_at ASC, pp.id ASC
`

type ListConfirmedParticipantPreviewsByPlayRow struct {
	ID            int64
	PlayID        string
	UserID        *string
	GuestName     *string
	RatingCode    *string
	DisplayName   *string
	PhotoUrl      *string
	SportsProfile *string
}

func (q *Queries) ListConfirmedParticipantPreviewsByPlay(ctx context.Context, playID string) ([]ListConfirmedParticipantPreviewsByPlayRow, error) {
	rows, err := q.db.QueryContext(ctx, listConfirmedParticipantPreviewsByPlay, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConfirmedParticipantPreviewsByPlayRow
	for rows.Next() {
		var i ListConfirmedParticipantPreviewsByPlayRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.DisplayName,
			&i.PhotoUrl,
			&i.SportsProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfirmedParticipantPreviewsByPlays = `-- name: ListConfirmedParticipantPreviewsByPlays :many
SELECT
    pp.id,
    pp.play_id,
    pp.user_id,
    pp.guest_name,
    pp.rating_code,
    u.display_name,
    u.photo_url,
    u.sports_profile
FROM play_participants pp
LEFT JOIN users u ON u.id = pp.user_id
WHERE pp.play_id IN (/*SLICE:play_ids*/?) AND pp.status = 'confirmed'
ORDER BY pp.play_id ASC, pp.created_at ASC, pp.id ASC
`

type ListConfirmedParticipantPreviewsByPlaysRow struct {
	ID            int64
	PlayID        string
	UserID        *string
	GuestName     *string
	RatingCode    *string
	DisplayName   *string
	PhotoUrl      *string
	SportsProfile *string
}

func (q *Queries) ListConfirmedParticipantPreviewsByPlays(ctx context.Context, playIds []string) ([]ListConfirmedParticipantPreviewsByPlaysRow, error) {
	query := listConfirmedParticipantPreviewsByPlays
	var queryParams []interface{}
	if len(playIds) > 0 {
		for _, v := range playIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:play_ids*/?", strings.Repeat(",?", len(playIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:play_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConfirmedParticipantPreviewsByPlaysRow
	for rows.Next() {
		var i ListConfirmedParticipantPreviewsByPlaysRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.DisplayName,
			&i.PhotoUrl,
			&i.SportsProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantPreviewsByPlayAndStatus = `-- name: ListParticipantPreviewsByPlayAndStatus :many
SELECT
    pp.id,
    pp.play_id,
    pp.user_id,
    pp.guest_name,
    pp.rating_code,
    u.display_name,
    u.photo_url,
    u.sports_profile
FROM play_participants pp
LEFT JOIN users u ON u.id = pp.user_id
WHERE pp.play_id = ? AND pp.status = ?
ORDER BY pp.created_at ASC, pp.id ASC
`

type ListParticipantPreviewsByPlayAndStatusParams struct {
	PlayID string
	Status model.PlayParticipantStatus
}

type ListParticipantPreviewsByPlayAndStatusRow struct {
	ID            int64
	PlayID        string
	UserID        *string
	GuestName     *string
	RatingCode    *string
	DisplayName   *string
	PhotoUrl      *string
	SportsProfile *string
}

func (q *Queries) ListParticipantPreviewsByPlayAndStatus(ctx context.Context, arg ListParticipantPreviewsByPlayAndStatusParams) ([]ListParticipantPreviewsByPlayAndStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantPreviewsByPlayAndStatus, arg.PlayID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantPreviewsByPlayAndStatusRow
	for rows.Next() {
		var i ListParticipantPreviewsByPlayAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.DisplayName,
			&i.PhotoUrl,
			&i.SportsProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantsByPlay = `-- name: ListPlayParticipantsByPlay :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ?
ORDER BY
    CASE status
        WHEN 'confirmed' THEN 1
        WHEN 'waitlisted' THEN 2
        ELSE 4
    END,
    created_at ASC,
    id ASC
`

func (q *Queries) ListPlayParticipantsByPlay(ctx context.Context, playID string) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByPlay, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantsByPlayAndStatus = `-- name: ListPlayParticipantsByPlayAndStatus :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ? AND status = ?
ORDER BY created_at ASC, id ASC
`

type ListPlayParticipantsByPlayAndStatusParams struct {
	PlayID string
	Status model.PlayParticipantStatus
}

func (q *Queries) ListPlayParticipantsByPlayAndStatus(ctx context.Context, arg ListPlayParticipantsByPlayAndStatusParams) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByPlayAndStatus, arg.PlayID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantsByUser = `-- name: ListPlayParticipantsByUser :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPlayParticipantsByUser(ctx context.Context, userID *string) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayParticipantStatus = `-- name: UpdatePlayParticipantStatus :one
UPDATE play_participants
SET
    status = ?,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?
RETURNING id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at
`

type UpdatePlayParticipantStatusParams struct {
	Status model.PlayParticipantStatus
	ID     int64
}

func (q *Queries) UpdatePlayParticipantStatus(ctx context.Context, arg UpdatePlayParticipantStatusParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, updatePlayParticipantStatus, arg.Status, arg.ID)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
