// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_reviews.sql

package db

import (
	"context"
	"time"

	"openplays/server/internal/model"
)

const getUserRatingAggregate = `-- name: GetUserRatingAggregate :one
SELECT
    CAST(COALESCE(AVG(rating), 0) AS REAL) AS average,
    COUNT(rating) AS rating_count
FROM play_reviews
WHERE reviewee_user_id = ? AND rating IS NOT NULL
`

type GetUserRatingAggregateRow struct {
	Average     float64
	RatingCount int64
}

// Ratings are anonymous: only the aggregate ever leaves the database.
func (q *Queries) GetUserRatingAggregate(ctx context.Context, revieweeUserID string) (GetUserRatingAggregateRow, error) {
	row := q.db.QueryRowContext(ctx, getUserRatingAggregate, revieweeUserID)
	var i GetUserRatingAggregateRow
	err := row.Scan(&i.Average, &i.RatingCount)
	return i, err
}

const listMyPlayReviews = `-- name: ListMyPlayReviews :many
SELECT id, play_id, reviewer_user_id, reviewee_user_id, rating, props, shoutout, created_at, updated_at FROM play_reviews
WHERE play_id = ? AND reviewer_user_id = ?
ORDER BY reviewee_user_id ASC
`

type ListMyPlayReviewsParams struct {
	PlayID         string
	ReviewerUserID string
}

func (q *Queries) ListMyPlayReviews(ctx context.Context, arg ListMyPlayReviewsParams) ([]PlayReview, error) {
	rows, err := q.db.QueryContext(ctx, listMyPlayReviews, arg.PlayID, arg.ReviewerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayReview
	for rows.Next() {
		var i PlayReview
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.ReviewerUserID,
			&i.RevieweeUserID,
			&i.Rating,
			&i.Props,
			&i.Shoutout,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlaysNeedingReviewPrompt = `-- name: ListPlaysNeedingReviewPrompt :many
SELECT
    p.id,
    p.name,
    COALESCE(v.name, NULLIF(p.venue, ''), 'No venue') AS venue_name,
    p.sport
FROM plays p
LEFT JOIN venues v ON v.id = p.venue_id
WHERE p.cancelled_at IS NULL
  AND p.created_by IS NOT NULL
  AND p.ends_at <= strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now', '-72 hours')
ORDER BY p.ends_at ASC
`

type ListPlaysNeedingReviewPromptRow struct {
	ID        string
	Name      *string
	VenueName string
	Sport     model.Sport
}

// Ended plays whose participants are due the review nudge. The prompter's
// ticks are aligned a minute past five-minute marks, so no extra delay is
// needed here; the 72h lower bound keeps the scan small and stops plays that
// ended before this feature shipped from prompting.
func (q *Queries) ListPlaysNeedingReviewPrompt(ctx context.Context) ([]ListPlaysNeedingReviewPromptRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlaysNeedingReviewPrompt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaysNeedingReviewPromptRow
	for rows.Next() {
		var i ListPlaysNeedingReviewPromptRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VenueName,
			&i.Sport,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewEligibleUsersByPlay = `-- name: ListReviewEligibleUsersByPlay :many
SELECT
    u.id,
    u.display_name,
    u.username,
    u.photo_url,
    CAST(EXISTS (
        SELECT 1 FROM play_hosts ph2
        WHERE ph2.play_id = ?1 AND ph2.user_id = u.id
    ) AS INTEGER) AS is_host
FROM users u
WHERE u.status = 'active'
  AND u.id IN (
      SELECT pp.user_id FROM play_participants pp
      WHERE pp.play_id = ?1
        AND pp.user_id IS NOT NULL
        AND pp.status IN ('confirmed', 'added')
      UNION
      SELECT ph.user_id FROM play_hosts ph
      WHERE ph.play_id = ?1
  )
ORDER BY u.display_name ASC, u.id ASC
`

type ListReviewEligibleUsersByPlayRow struct {
	ID          string
	DisplayName string
	Username    *string
	PhotoUrl    *string
	IsHost      int64
}

// The single source of truth for who can review and be reviewed on a play:
// active registered users holding a reserved spot (confirmed or added) plus
// the play hosts. Guests have no account and are excluded.
func (q *Queries) ListReviewEligibleUsersByPlay(ctx context.Context, playID string) ([]ListReviewEligibleUsersByPlayRow, error) {
	rows, err := q.db.QueryContext(ctx, listReviewEligibleUsersByPlay, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReviewEligibleUsersByPlayRow
	for rows.Next() {
		var i ListReviewEligibleUsersByPlayRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Username,
			&i.PhotoUrl,
			&i.IsHost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPropCounts = `-- name: ListUserPropCounts :many
SELECT
    p.sport,
    CAST(je.value AS TEXT) AS prop,
    COUNT(*) AS prop_count
FROM play_reviews r
JOIN plays p ON p.id = r.play_id
CROSS JOIN json_each(r.props) je
WHERE r.reviewee_user_id = ?
GROUP BY p.sport, je.value
ORDER BY p.sport ASC, prop_count DESC, prop ASC
`

type ListUserPropCountsRow struct {
	Sport     model.Sport
	Prop      string
	PropCount int64
}

// Props are sport-linked: each given prop counts toward the sport of the
// play it was earned in.
func (q *Queries) ListUserPropCounts(ctx context.Context, revieweeUserID string) ([]ListUserPropCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserPropCounts, revieweeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserPropCountsRow
	for rows.Next() {
		var i ListUserPropCountsRow
		if err := rows.Scan(&i.Sport, &i.Prop, &i.PropCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRatingDistribution = `-- name: ListUserRatingDistribution :many
SELECT
    rating,
    COUNT(*) AS rating_count
FROM play_reviews
WHERE reviewee_user_id = ? AND rating IS NOT NULL
GROUP BY rating
ORDER BY rating ASC
`

type ListUserRatingDistributionRow struct {
	Rating      *int64
	RatingCount int64
}

// Star breakdown for the profile's rating chart; still anonymous.
func (q *Queries) ListUserRatingDistribution(ctx context.Context, revieweeUserID string) ([]ListUserRatingDistributionRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserRatingDistribution, revieweeUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRatingDistributionRow
	for rows.Next() {
		var i ListUserRatingDistributionRow
		if err := rows.Scan(&i.Rating, &i.RatingCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserShoutouts = `-- name: ListUserShoutouts :many
SELECT
    r.shoutout,
    r.created_at,
    u.display_name AS reviewer_display_name,
    u.username AS reviewer_username,
    u.photo_url AS reviewer_photo_url,
    p.id AS play_id,
    p.sport,
    p.name AS play_name,
    p.starts_at,
    p.timezone
FROM play_reviews r
JOIN users u ON u.id = r.reviewer_user_id AND u.status = 'active'
JOIN plays p ON p.id = r.play_id
WHERE r.reviewee_user_id = ? AND r.shoutout IS NOT NULL
ORDER BY r.created_at DESC, r.id DESC
LIMIT ?
`

type ListUserShoutoutsParams struct {
	RevieweeUserID string
	Limit          int64
}

type ListUserShoutoutsRow struct {
	Shoutout            *string
	CreatedAt           time.Time
	ReviewerDisplayName string
	ReviewerUsername    *string
	ReviewerPhotoUrl    *string
	PlayID              string
	Sport               model.Sport
	PlayName            *string
	StartsAt            time.Time
	Timezone            string
}

// Shoutouts are attributed by design; the review's rating is never selected.
func (q *Queries) ListUserShoutouts(ctx context.Context, arg ListUserShoutoutsParams) ([]ListUserShoutoutsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserShoutouts, arg.RevieweeUserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserShoutoutsRow
	for rows.Next() {
		var i ListUserShoutoutsRow
		if err := rows.Scan(
			&i.Shoutout,
			&i.CreatedAt,
			&i.ReviewerDisplayName,
			&i.ReviewerUsername,
			&i.ReviewerPhotoUrl,
			&i.PlayID,
			&i.Sport,
			&i.PlayName,
			&i.StartsAt,
			&i.Timezone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReviewPromptSent = `-- name: MarkReviewPromptSent :execrows
INSERT OR IGNORE INTO play_review_prompts (play_id, user_id)
VALUES (?, ?)
`

type MarkReviewPromptSentParams struct {
	PlayID string
	UserID string
}

func (q *Queries) MarkReviewPromptSent(ctx context.Context, arg MarkReviewPromptSentParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, markReviewPromptSent, arg.PlayID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const upsertPlayReview = `-- name: UpsertPlayReview :one
INSERT INTO play_reviews (
    play_id, reviewer_user_id, reviewee_user_id, rating, props, shoutout
) VALUES (
    ?, ?, ?, ?, ?, ?
)
ON CONFLICT (play_id, reviewer_user_id, reviewee_user_id) DO UPDATE SET
    rating = excluded.rating,
    props = excluded.props,
    shoutout = excluded.shoutout,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
RETURNING id, play_id, reviewer_user_id, reviewee_user_id, rating, props, shoutout, created_at, updated_at
`

type UpsertPlayReviewParams struct {
	PlayID         string
	ReviewerUserID string
	RevieweeUserID string
	Rating         *int64
	Props          string
	Shoutout       *string
}

func (q *Queries) UpsertPlayReview(ctx context.Context, arg UpsertPlayReviewParams) (PlayReview, error) {
	row := q.db.QueryRowContext(ctx, upsertPlayReview,
		arg.PlayID,
		arg.ReviewerUserID,
		arg.RevieweeUserID,
		arg.Rating,
		arg.Props,
		arg.Shoutout,
	)
	var i PlayReview
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.ReviewerUserID,
		&i.RevieweeUserID,
		&i.Rating,
		&i.Props,
		&i.Shoutout,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
