// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_participants.sql

package db

import (
	"context"

	"openplays/server/internal/model"
)

const countConfirmedPlayParticipants = `-- name: CountConfirmedPlayParticipants :one
SELECT COUNT(*) FROM play_participants
WHERE play_id = ? AND status = 'confirmed'
`

func (q *Queries) CountConfirmedPlayParticipants(ctx context.Context, playID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfirmedPlayParticipants, playID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayParticipantsByStatus = `-- name: CountPlayParticipantsByStatus :one
SELECT COUNT(*) FROM play_participants
WHERE play_id = ? AND status = ?
`

type CountPlayParticipantsByStatusParams struct {
	PlayID string
	Status model.PlayParticipantStatus
}

func (q *Queries) CountPlayParticipantsByStatus(ctx context.Context, arg CountPlayParticipantsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayParticipantsByStatus, arg.PlayID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlayParticipant = `-- name: CreatePlayParticipant :one
INSERT INTO play_participants (
    play_id, user_id, guest_name, rating_code, rating_ord, status
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at
`

type CreatePlayParticipantParams struct {
	PlayID     string
	UserID     *string
	GuestName  *string
	RatingCode *string
	RatingOrd  *int64
	Status     model.PlayParticipantStatus
}

func (q *Queries) CreatePlayParticipant(ctx context.Context, arg CreatePlayParticipantParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, createPlayParticipant,
		arg.PlayID,
		arg.UserID,
		arg.GuestName,
		arg.RatingCode,
		arg.RatingOrd,
		arg.Status,
	)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayParticipant = `-- name: DeletePlayParticipant :exec
DELETE FROM play_participants
WHERE id = ?
`

func (q *Queries) DeletePlayParticipant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayParticipant, id)
	return err
}

const deletePlayParticipantByPlayAndUser = `-- name: DeletePlayParticipantByPlayAndUser :exec
DELETE FROM play_participants
WHERE play_id = ? AND user_id = ?
`

type DeletePlayParticipantByPlayAndUserParams struct {
	PlayID string
	UserID *string
}

func (q *Queries) DeletePlayParticipantByPlayAndUser(ctx context.Context, arg DeletePlayParticipantByPlayAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deletePlayParticipantByPlayAndUser, arg.PlayID, arg.UserID)
	return err
}

const getPlayParticipantByID = `-- name: GetPlayParticipantByID :one
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE id = ?
`

func (q *Queries) GetPlayParticipantByID(ctx context.Context, id int64) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, getPlayParticipantByID, id)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayParticipantByPlayAndUser = `-- name: GetPlayParticipantByPlayAndUser :one
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ? AND user_id = ?
`

type GetPlayParticipantByPlayAndUserParams struct {
	PlayID string
	UserID *string
}

func (q *Queries) GetPlayParticipantByPlayAndUser(ctx context.Context, arg GetPlayParticipantByPlayAndUserParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, getPlayParticipantByPlayAndUser, arg.PlayID, arg.UserID)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayParticipantsByPlay = `-- name: ListPlayParticipantsByPlay :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ?
ORDER BY
    CASE status
        WHEN 'confirmed' THEN 1
        WHEN 'waitlisted' THEN 2
        ELSE 4
    END,
    created_at ASC,
    id ASC
`

func (q *Queries) ListPlayParticipantsByPlay(ctx context.Context, playID string) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByPlay, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantsByPlayAndStatus = `-- name: ListPlayParticipantsByPlayAndStatus :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ? AND status = ?
ORDER BY created_at ASC, id ASC
`

type ListPlayParticipantsByPlayAndStatusParams struct {
	PlayID string
	Status model.PlayParticipantStatus
}

func (q *Queries) ListPlayParticipantsByPlayAndStatus(ctx context.Context, arg ListPlayParticipantsByPlayAndStatusParams) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByPlayAndStatus, arg.PlayID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantsByUser = `-- name: ListPlayParticipantsByUser :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPlayParticipantsByUser(ctx context.Context, userID *string) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayParticipantStatus = `-- name: UpdatePlayParticipantStatus :one
UPDATE play_participants
SET
    status = ?,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?
RETURNING id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at
`

type UpdatePlayParticipantStatusParams struct {
	Status model.PlayParticipantStatus
	ID     int64
}

func (q *Queries) UpdatePlayParticipantStatus(ctx context.Context, arg UpdatePlayParticipantStatusParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, updatePlayParticipantStatus, arg.Status, arg.ID)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
