// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_hosts.sql

package db

import (
	"context"
	"strings"
)

const createPlayHost = `-- name: CreatePlayHost :one
INSERT INTO play_hosts (
    play_id, user_id
) VALUES (
    ?, ?
)
ON CONFLICT(play_id, user_id) DO UPDATE SET
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
RETURNING play_id, user_id, created_at, updated_at
`

type CreatePlayHostParams struct {
	PlayID string
	UserID string
}

func (q *Queries) CreatePlayHost(ctx context.Context, arg CreatePlayHostParams) (PlayHost, error) {
	row := q.db.QueryRowContext(ctx, createPlayHost, arg.PlayID, arg.UserID)
	var i PlayHost
	err := row.Scan(
		&i.PlayID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayHostsByPlay = `-- name: DeletePlayHostsByPlay :exec
DELETE FROM play_hosts
WHERE play_id = ?
`

func (q *Queries) DeletePlayHostsByPlay(ctx context.Context, playID string) error {
	_, err := q.db.ExecContext(ctx, deletePlayHostsByPlay, playID)
	return err
}

const getPlayHost = `-- name: GetPlayHost :one
SELECT play_id, user_id, created_at, updated_at FROM play_hosts
WHERE play_id = ? AND user_id = ?
`

type GetPlayHostParams struct {
	PlayID string
	UserID string
}

func (q *Queries) GetPlayHost(ctx context.Context, arg GetPlayHostParams) (PlayHost, error) {
	row := q.db.QueryRowContext(ctx, getPlayHost, arg.PlayID, arg.UserID)
	var i PlayHost
	err := row.Scan(
		&i.PlayID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPlayHostUserIDsByPlay = `-- name: ListPlayHostUserIDsByPlay :many
SELECT user_id FROM play_hosts
WHERE play_id = ?
ORDER BY created_at ASC, user_id ASC
`

func (q *Queries) ListPlayHostUserIDsByPlay(ctx context.Context, playID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listPlayHostUserIDsByPlay, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayHostUserIDsByPlays = `-- name: ListPlayHostUserIDsByPlays :many
SELECT play_id, user_id FROM play_hosts
WHERE play_id IN (/*SLICE:play_ids*/?)
ORDER BY play_id ASC, created_at ASC, user_id ASC
`

type ListPlayHostUserIDsByPlaysRow struct {
	PlayID string
	UserID string
}

func (q *Queries) ListPlayHostUserIDsByPlays(ctx context.Context, playIds []string) ([]ListPlayHostUserIDsByPlaysRow, error) {
	query := listPlayHostUserIDsByPlays
	var queryParams []interface{}
	if len(playIds) > 0 {
		for _, v := range playIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:play_ids*/?", strings.Repeat(",?", len(playIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:play_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayHostUserIDsByPlaysRow
	for rows.Next() {
		var i ListPlayHostUserIDsByPlaysRow
		if err := rows.Scan(&i.PlayID, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
