// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_participants.sql

package db

import (
	"context"
	"strings"

	"openplays/server/internal/model"
)

const countConfirmedPlayParticipants = `-- name: CountConfirmedPlayParticipants :one
SELECT COUNT(*) FROM play_participants
WHERE play_id = ? AND status = 'confirmed'
`

func (q *Queries) CountConfirmedPlayParticipants(ctx context.Context, playID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfirmedPlayParticipants, playID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlayParticipantsByStatus = `-- name: CountPlayParticipantsByStatus :one
SELECT COUNT(*) FROM play_participants
WHERE play_id = ? AND status = ?
`

type CountPlayParticipantsByStatusParams struct {
	PlayID string
	Status model.PlayParticipantStatus
}

func (q *Queries) CountPlayParticipantsByStatus(ctx context.Context, arg CountPlayParticipantsByStatusParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlayParticipantsByStatus, arg.PlayID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReservedPlayParticipants = `-- name: CountReservedPlayParticipants :one
SELECT COUNT(*) FROM play_participants
WHERE play_id = ? AND status IN ('confirmed', 'added')
`

func (q *Queries) CountReservedPlayParticipants(ctx context.Context, playID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReservedPlayParticipants, playID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlayParticipant = `-- name: CreatePlayParticipant :one
INSERT INTO play_participants (
    play_id, user_id, guest_name, rating_code, rating_ord, status
) VALUES (
    ?, ?, ?, ?, ?, ?
)
RETURNING id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at
`

type CreatePlayParticipantParams struct {
	PlayID     string
	UserID     *string
	GuestName  *string
	RatingCode *string
	RatingOrd  *int64
	Status     model.PlayParticipantStatus
}

func (q *Queries) CreatePlayParticipant(ctx context.Context, arg CreatePlayParticipantParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, createPlayParticipant,
		arg.PlayID,
		arg.UserID,
		arg.GuestName,
		arg.RatingCode,
		arg.RatingOrd,
		arg.Status,
	)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePlayParticipant = `-- name: DeletePlayParticipant :exec
DELETE FROM play_participants
WHERE id = ?
`

func (q *Queries) DeletePlayParticipant(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePlayParticipant, id)
	return err
}

const deletePlayParticipantByPlayAndUser = `-- name: DeletePlayParticipantByPlayAndUser :exec
DELETE FROM play_participants
WHERE play_id = ? AND user_id = ?
`

type DeletePlayParticipantByPlayAndUserParams struct {
	PlayID string
	UserID *string
}

func (q *Queries) DeletePlayParticipantByPlayAndUser(ctx context.Context, arg DeletePlayParticipantByPlayAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deletePlayParticipantByPlayAndUser, arg.PlayID, arg.UserID)
	return err
}

const deletePlayParticipantsByPlay = `-- name: DeletePlayParticipantsByPlay :exec
DELETE FROM play_participants
WHERE play_id = ?
`

func (q *Queries) DeletePlayParticipantsByPlay(ctx context.Context, playID string) error {
	_, err := q.db.ExecContext(ctx, deletePlayParticipantsByPlay, playID)
	return err
}

const getPlayParticipantByID = `-- name: GetPlayParticipantByID :one
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE id = ?
`

func (q *Queries) GetPlayParticipantByID(ctx context.Context, id int64) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, getPlayParticipantByID, id)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlayParticipantByPlayAndUser = `-- name: GetPlayParticipantByPlayAndUser :one
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ? AND user_id = ?
`

type GetPlayParticipantByPlayAndUserParams struct {
	PlayID string
	UserID *string
}

func (q *Queries) GetPlayParticipantByPlayAndUser(ctx context.Context, arg GetPlayParticipantByPlayAndUserParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, getPlayParticipantByPlayAndUser, arg.PlayID, arg.UserID)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listParticipantPreviewsByPlay = `-- name: ListParticipantPreviewsByPlay :many
SELECT
    pp.id,
    pp.play_id,
    pp.user_id,
    pp.guest_name,
    pp.rating_code,
    pp.status,
    u.display_name,
    u.username,
    u.photo_url,
    u.sports_profile
FROM play_participants pp
LEFT JOIN users u ON u.id = pp.user_id
WHERE pp.play_id = ?
ORDER BY pp.created_at ASC, pp.id ASC
`

type ListParticipantPreviewsByPlayRow struct {
	ID            int64
	PlayID        string
	UserID        *string
	GuestName     *string
	RatingCode    *string
	Status        model.PlayParticipantStatus
	DisplayName   *string
	Username      *string
	PhotoUrl      *string
	SportsProfile *string
}

// The full roster for the play detail page, partitioned by status in Go.
func (q *Queries) ListParticipantPreviewsByPlay(ctx context.Context, playID string) ([]ListParticipantPreviewsByPlayRow, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantPreviewsByPlay, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListParticipantPreviewsByPlayRow
	for rows.Next() {
		var i ListParticipantPreviewsByPlayRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.Status,
			&i.DisplayName,
			&i.Username,
			&i.PhotoUrl,
			&i.SportsProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantStatesByUserAndPlays = `-- name: ListPlayParticipantStatesByUserAndPlays :many
SELECT play_id, status
FROM play_participants
WHERE user_id = ? AND play_id IN (/*SLICE:play_ids*/?)
`

type ListPlayParticipantStatesByUserAndPlaysParams struct {
	UserID  *string
	PlayIds []string
}

type ListPlayParticipantStatesByUserAndPlaysRow struct {
	PlayID string
	Status model.PlayParticipantStatus
}

func (q *Queries) ListPlayParticipantStatesByUserAndPlays(ctx context.Context, arg ListPlayParticipantStatesByUserAndPlaysParams) ([]ListPlayParticipantStatesByUserAndPlaysRow, error) {
	query := listPlayParticipantStatesByUserAndPlays
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.PlayIds) > 0 {
		for _, v := range arg.PlayIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:play_ids*/?", strings.Repeat(",?", len(arg.PlayIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:play_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayParticipantStatesByUserAndPlaysRow
	for rows.Next() {
		var i ListPlayParticipantStatesByUserAndPlaysRow
		if err := rows.Scan(&i.PlayID, &i.Status); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantsByPlay = `-- name: ListPlayParticipantsByPlay :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ?
ORDER BY
    CASE status
        WHEN 'confirmed' THEN 1
        WHEN 'added' THEN 2
        WHEN 'requested' THEN 3
        WHEN 'waitlisted' THEN 4
        ELSE 5
    END,
    created_at ASC,
    id ASC
`

func (q *Queries) ListPlayParticipantsByPlay(ctx context.Context, playID string) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByPlay, playID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantsByPlayAndStatus = `-- name: ListPlayParticipantsByPlayAndStatus :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE play_id = ? AND status = ?
ORDER BY created_at ASC, id ASC
`

type ListPlayParticipantsByPlayAndStatusParams struct {
	PlayID string
	Status model.PlayParticipantStatus
}

func (q *Queries) ListPlayParticipantsByPlayAndStatus(ctx context.Context, arg ListPlayParticipantsByPlayAndStatusParams) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByPlayAndStatus, arg.PlayID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayParticipantsByUser = `-- name: ListPlayParticipantsByUser :many
SELECT id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at FROM play_participants
WHERE user_id = ?
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListPlayParticipantsByUser(ctx context.Context, userID *string) ([]PlayParticipant, error) {
	rows, err := q.db.QueryContext(ctx, listPlayParticipantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayParticipant
	for rows.Next() {
		var i PlayParticipant
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.RatingOrd,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRosteredParticipantPreviewsByPlays = `-- name: ListRosteredParticipantPreviewsByPlays :many
SELECT
    pp.id,
    pp.play_id,
    pp.user_id,
    pp.guest_name,
    pp.rating_code,
    u.display_name,
    u.username,
    u.photo_url,
    u.sports_profile
FROM play_participants pp
LEFT JOIN users u ON u.id = pp.user_id
WHERE pp.play_id IN (/*SLICE:play_ids*/?) AND pp.status IN ('confirmed', 'added')
ORDER BY
    pp.play_id ASC,
    CASE pp.status WHEN 'confirmed' THEN 1 ELSE 2 END,
    pp.created_at ASC,
    pp.id ASC
`

type ListRosteredParticipantPreviewsByPlaysRow struct {
	ID            int64
	PlayID        string
	UserID        *string
	GuestName     *string
	RatingCode    *string
	DisplayName   *string
	Username      *string
	PhotoUrl      *string
	SportsProfile *string
}

// Card previews cover the slot-reserving roster: confirmed and added players.
func (q *Queries) ListRosteredParticipantPreviewsByPlays(ctx context.Context, playIds []string) ([]ListRosteredParticipantPreviewsByPlaysRow, error) {
	query := listRosteredParticipantPreviewsByPlays
	var queryParams []interface{}
	if len(playIds) > 0 {
		for _, v := range playIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:play_ids*/?", strings.Repeat(",?", len(playIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:play_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRosteredParticipantPreviewsByPlaysRow
	for rows.Next() {
		var i ListRosteredParticipantPreviewsByPlaysRow
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.UserID,
			&i.GuestName,
			&i.RatingCode,
			&i.DisplayName,
			&i.Username,
			&i.PhotoUrl,
			&i.SportsProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePlayParticipantStatus = `-- name: UpdatePlayParticipantStatus :one
UPDATE play_participants
SET
    status = ?,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?
RETURNING id, play_id, user_id, guest_name, rating_code, rating_ord, status, created_at, updated_at
`

type UpdatePlayParticipantStatusParams struct {
	Status model.PlayParticipantStatus
	ID     int64
}

func (q *Queries) UpdatePlayParticipantStatus(ctx context.Context, arg UpdatePlayParticipantStatusParams) (PlayParticipant, error) {
	row := q.db.QueryRowContext(ctx, updatePlayParticipantStatus, arg.Status, arg.ID)
	var i PlayParticipant
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.UserID,
		&i.GuestName,
		&i.RatingCode,
		&i.RatingOrd,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
