// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plays.sql

package db

import (
	"context"
	"time"

	"openplays/server/internal/model"
)

const getUpcomingPlays = `-- name: GetUpcomingPlays :many
SELECT id, created_at, updated_at, listing_type, sport, game_type, host_name, starts_at, ends_at, timezone, venue, venue_norm, level_min, level_max, level_min_ord, level_max_ord, fee, currency, max_players, slots_left, courts, contacts, gender_pref, meta, source, source_sender_username, source_raw_message, source_message_time, venue_postal_code FROM plays
WHERE starts_at > CURRENT_TIMESTAMP
  AND listing_type = 'play'
ORDER BY starts_at ASC
`

func (q *Queries) GetUpcomingPlays(ctx context.Context) ([]Play, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingPlays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListingType,
			&i.Sport,
			&i.GameType,
			&i.HostName,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.Venue,
			&i.VenueNorm,
			&i.LevelMin,
			&i.LevelMax,
			&i.LevelMinOrd,
			&i.LevelMaxOrd,
			&i.Fee,
			&i.Currency,
			&i.MaxPlayers,
			&i.SlotsLeft,
			&i.Courts,
			&i.Contacts,
			&i.GenderPref,
			&i.Meta,
			&i.Source,
			&i.SourceSenderUsername,
			&i.SourceRawMessage,
			&i.SourceMessageTime,
			&i.VenuePostalCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPlay = `-- name: UpsertPlay :one
INSERT INTO plays (
    listing_type, sport, game_type, host_name,
    starts_at, ends_at, timezone,
    venue, venue_norm, venue_postal_code,
    level_min, level_max, level_min_ord, level_max_ord,
    fee, currency, max_players, slots_left, courts,
    contacts, gender_pref, meta,
    source, source_sender_username, source_raw_message, source_message_time
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?,
    ?, ?, ?, ?, ?,
    ?, ?, ?,
    ?, ?, ?, ?
)
ON CONFLICT(host_name, starts_at, ends_at, sport, venue_postal_code) DO UPDATE SET
    listing_type          = excluded.listing_type,
    game_type             = excluded.game_type,
    venue                 = excluded.venue,
    venue_norm            = excluded.venue_norm,
    level_min             = excluded.level_min,
    level_max             = excluded.level_max,
    level_min_ord         = excluded.level_min_ord,
    level_max_ord         = excluded.level_max_ord,
    fee                   = excluded.fee,
    currency              = excluded.currency,
    max_players           = excluded.max_players,
    slots_left            = excluded.slots_left,
    courts                = excluded.courts,
    contacts              = excluded.contacts,
    gender_pref           = excluded.gender_pref,
    meta                  = excluded.meta,
    source_sender_username = excluded.source_sender_username,
    source_raw_message    = excluded.source_raw_message,
    source_message_time   = excluded.source_message_time,
    updated_at            = CURRENT_TIMESTAMP
RETURNING id, created_at, updated_at, listing_type, sport, game_type, host_name, starts_at, ends_at, timezone, venue, venue_norm, level_min, level_max, level_min_ord, level_max_ord, fee, currency, max_players, slots_left, courts, contacts, gender_pref, meta, source, source_sender_username, source_raw_message, source_message_time, venue_postal_code
`

type UpsertPlayParams struct {
	ListingType          model.ListingType
	Sport                model.Sport
	GameType             *model.GameType
	HostName             string
	StartsAt             time.Time
	EndsAt               time.Time
	Timezone             string
	Venue                string
	VenueNorm            string
	VenuePostalCode      *string
	LevelMin             *string
	LevelMax             *string
	LevelMinOrd          *int64
	LevelMaxOrd          *int64
	Fee                  *int64
	Currency             string
	MaxPlayers           *int64
	SlotsLeft            *int64
	Courts               *int64
	Contacts             model.Contacts
	GenderPref           *model.GenderPref
	Meta                 model.Meta
	Source               *string
	SourceSenderUsername *string
	SourceRawMessage     *string
	SourceMessageTime    *time.Time
}

func (q *Queries) UpsertPlay(ctx context.Context, arg UpsertPlayParams) (Play, error) {
	row := q.db.QueryRowContext(ctx, upsertPlay,
		arg.ListingType,
		arg.Sport,
		arg.GameType,
		arg.HostName,
		arg.StartsAt,
		arg.EndsAt,
		arg.Timezone,
		arg.Venue,
		arg.VenueNorm,
		arg.VenuePostalCode,
		arg.LevelMin,
		arg.LevelMax,
		arg.LevelMinOrd,
		arg.LevelMaxOrd,
		arg.Fee,
		arg.Currency,
		arg.MaxPlayers,
		arg.SlotsLeft,
		arg.Courts,
		arg.Contacts,
		arg.GenderPref,
		arg.Meta,
		arg.Source,
		arg.SourceSenderUsername,
		arg.SourceRawMessage,
		arg.SourceMessageTime,
	)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ListingType,
		&i.Sport,
		&i.GameType,
		&i.HostName,
		&i.StartsAt,
		&i.EndsAt,
		&i.Timezone,
		&i.Venue,
		&i.VenueNorm,
		&i.LevelMin,
		&i.LevelMax,
		&i.LevelMinOrd,
		&i.LevelMaxOrd,
		&i.Fee,
		&i.Currency,
		&i.MaxPlayers,
		&i.SlotsLeft,
		&i.Courts,
		&i.Contacts,
		&i.GenderPref,
		&i.Meta,
		&i.Source,
		&i.SourceSenderUsername,
		&i.SourceRawMessage,
		&i.SourceMessageTime,
		&i.VenuePostalCode,
	)
	return i, err
}
