// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_favourites.sql

package db

import (
	"context"
	"strings"
	"time"

	"openplays/server/internal/model"
)

const countFavouriteUpcomingPlays = `-- name: CountFavouriteUpcomingPlays :one
SELECT COUNT(*)
FROM play_favourites pf
INNER JOIN plays p ON p.id = pf.play_id
WHERE pf.user_id = ?1
  AND p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.cancelled_at IS NULL
`

func (q *Queries) CountFavouriteUpcomingPlays(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFavouriteUpcomingPlays, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const favouritePlay = `-- name: FavouritePlay :exec
INSERT OR IGNORE INTO play_favourites (user_id, play_id)
VALUES (?, ?)
`

type FavouritePlayParams struct {
	UserID string
	PlayID string
}

func (q *Queries) FavouritePlay(ctx context.Context, arg FavouritePlayParams) error {
	_, err := q.db.ExecContext(ctx, favouritePlay, arg.UserID, arg.PlayID)
	return err
}

const getFavouriteablePlayID = `-- name: GetFavouriteablePlayID :one
SELECT id
FROM plays
WHERE id = ?
  AND ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND cancelled_at IS NULL
`

func (q *Queries) GetFavouriteablePlayID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getFavouriteablePlayID, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const listFavouriteUpcomingPlays = `-- name: ListFavouriteUpcomingPlays :many
SELECT
    p.id, p.created_at, p.updated_at,
    p.listing_type, p.sport, p.game_type, p.host_name, p.name, p.description,
    p.starts_at, p.ends_at, p.timezone,
    p.venue, p.venue_id, p.created_by, p.cancelled_at,
    p.level_min, p.level_max, p.level_min_ord, p.level_max_ord,
    p.fee, p.currency, p.max_players, p.slots_left, p.courts,
    p.contacts, p.gender_pref, p.meta,
    p.source, p.source_sender_username, p.source_message_id, p.source_group,
    COALESCE(v.name, NULLIF(p.venue, ''), 'No venue') AS venue_name, v.postal_code AS venue_postal_code,
    v.latitude AS venue_latitude, v.longitude AS venue_longitude, v.google_place_id AS venue_google_place_id,
    u.display_name AS creator_display_name, u.username AS creator_username, u.photo_url AS creator_photo_url
FROM play_favourites pf
INNER JOIN plays p ON p.id = pf.play_id
LEFT JOIN venues v ON v.id = p.venue_id
LEFT JOIN users u ON u.id = p.created_by
WHERE pf.user_id = ?1
  AND p.ends_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
  AND p.cancelled_at IS NULL
  AND (?2 IS NULL
    OR p.starts_at > ?2
    OR (p.starts_at = ?2 AND p.id > ?3))
ORDER BY p.starts_at ASC, p.id ASC
LIMIT ?4
`

type ListFavouriteUpcomingPlaysParams struct {
	UserID         string
	CursorStartsAt interface{}
	CursorID       *string
	PageSize       int64
}

type ListFavouriteUpcomingPlaysRow struct {
	ID                   string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	ListingType          model.ListingType
	Sport                model.Sport
	GameType             *model.GameType
	HostName             string
	Name                 *string
	Description          *string
	StartsAt             time.Time
	EndsAt               time.Time
	Timezone             string
	Venue                string
	VenueID              *int64
	CreatedBy            *string
	CancelledAt          *time.Time
	LevelMin             *string
	LevelMax             *string
	LevelMinOrd          *int64
	LevelMaxOrd          *int64
	Fee                  *int64
	Currency             string
	MaxPlayers           *int64
	SlotsLeft            *int64
	Courts               *int64
	Contacts             model.Contacts
	GenderPref           *model.GenderPref
	Meta                 model.Meta
	Source               *string
	SourceSenderUsername *string
	SourceMessageID      *string
	SourceGroup          *string
	VenueName            string
	VenuePostalCode      *string
	VenueLatitude        *float64
	VenueLongitude       *float64
	VenueGooglePlaceID   *string
	CreatorDisplayName   *string
	CreatorUsername      *string
	CreatorPhotoUrl      *string
}

// Paginated upcoming listings favourited by the current user.
func (q *Queries) ListFavouriteUpcomingPlays(ctx context.Context, arg ListFavouriteUpcomingPlaysParams) ([]ListFavouriteUpcomingPlaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listFavouriteUpcomingPlays,
		arg.UserID,
		arg.CursorStartsAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavouriteUpcomingPlaysRow
	for rows.Next() {
		var i ListFavouriteUpcomingPlaysRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ListingType,
			&i.Sport,
			&i.GameType,
			&i.HostName,
			&i.Name,
			&i.Description,
			&i.StartsAt,
			&i.EndsAt,
			&i.Timezone,
			&i.Venue,
			&i.VenueID,
			&i.CreatedBy,
			&i.CancelledAt,
			&i.LevelMin,
			&i.LevelMax,
			&i.LevelMinOrd,
			&i.LevelMaxOrd,
			&i.Fee,
			&i.Currency,
			&i.MaxPlayers,
			&i.SlotsLeft,
			&i.Courts,
			&i.Contacts,
			&i.GenderPref,
			&i.Meta,
			&i.Source,
			&i.SourceSenderUsername,
			&i.SourceMessageID,
			&i.SourceGroup,
			&i.VenueName,
			&i.VenuePostalCode,
			&i.VenueLatitude,
			&i.VenueLongitude,
			&i.VenueGooglePlaceID,
			&i.CreatorDisplayName,
			&i.CreatorUsername,
			&i.CreatorPhotoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFavouritedPlayIDsByUserAndPlays = `-- name: ListFavouritedPlayIDsByUserAndPlays :many
SELECT play_id
FROM play_favourites
WHERE user_id = ? AND play_id IN (/*SLICE:play_ids*/?)
`

type ListFavouritedPlayIDsByUserAndPlaysParams struct {
	UserID  string
	PlayIds []string
}

func (q *Queries) ListFavouritedPlayIDsByUserAndPlays(ctx context.Context, arg ListFavouritedPlayIDsByUserAndPlaysParams) ([]string, error) {
	query := listFavouritedPlayIDsByUserAndPlays
	var queryParams []interface{}
	queryParams = append(queryParams, arg.UserID)
	if len(arg.PlayIds) > 0 {
		for _, v := range arg.PlayIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:play_ids*/?", strings.Repeat(",?", len(arg.PlayIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:play_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var play_id string
		if err := rows.Scan(&play_id); err != nil {
			return nil, err
		}
		items = append(items, play_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfavouritePlay = `-- name: UnfavouritePlay :exec
DELETE FROM play_favourites
WHERE user_id = ? AND play_id = ?
`

type UnfavouritePlayParams struct {
	UserID string
	PlayID string
}

func (q *Queries) UnfavouritePlay(ctx context.Context, arg UnfavouritePlayParams) error {
	_, err := q.db.ExecContext(ctx, unfavouritePlay, arg.UserID, arg.PlayID)
	return err
}
