// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: play_events.sql

package db

import (
	"context"

	"openplays/server/internal/model"
)

const createPlayEvent = `-- name: CreatePlayEvent :one
INSERT INTO play_events (
    play_id,
    event_type,
    actor_user_id,
    actor_display_name,
    subject_user_id,
    subject_display_name,
    participant_id,
    metadata
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, play_id, event_type, actor_user_id, actor_display_name, subject_user_id, subject_display_name, participant_id, metadata, created_at
`

type CreatePlayEventParams struct {
	PlayID             string
	EventType          model.PlayEventType
	ActorUserID        *string
	ActorDisplayName   *string
	SubjectUserID      *string
	SubjectDisplayName *string
	ParticipantID      *int64
	Metadata           *string
}

func (q *Queries) CreatePlayEvent(ctx context.Context, arg CreatePlayEventParams) (PlayEvent, error) {
	row := q.db.QueryRowContext(ctx, createPlayEvent,
		arg.PlayID,
		arg.EventType,
		arg.ActorUserID,
		arg.ActorDisplayName,
		arg.SubjectUserID,
		arg.SubjectDisplayName,
		arg.ParticipantID,
		arg.Metadata,
	)
	var i PlayEvent
	err := row.Scan(
		&i.ID,
		&i.PlayID,
		&i.EventType,
		&i.ActorUserID,
		&i.ActorDisplayName,
		&i.SubjectUserID,
		&i.SubjectDisplayName,
		&i.ParticipantID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listHostVisiblePlayEvents = `-- name: ListHostVisiblePlayEvents :many
SELECT id, play_id, event_type, actor_user_id, actor_display_name, subject_user_id, subject_display_name, participant_id, metadata, created_at FROM (
    SELECT id, play_id, event_type, actor_user_id, actor_display_name, subject_user_id, subject_display_name, participant_id, metadata, created_at
    FROM play_events
    WHERE play_id = ?
      AND event_type != 'play.created'
    ORDER BY created_at DESC, id DESC
    LIMIT ?
)
ORDER BY created_at ASC, id ASC
`

type ListHostVisiblePlayEventsParams struct {
	PlayID string
	Limit  int64
}

func (q *Queries) ListHostVisiblePlayEvents(ctx context.Context, arg ListHostVisiblePlayEventsParams) ([]PlayEvent, error) {
	rows, err := q.db.QueryContext(ctx, listHostVisiblePlayEvents, arg.PlayID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayEvent
	for rows.Next() {
		var i PlayEvent
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.EventType,
			&i.ActorUserID,
			&i.ActorDisplayName,
			&i.SubjectUserID,
			&i.SubjectDisplayName,
			&i.ParticipantID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listParticipantVisiblePlayEvents = `-- name: ListParticipantVisiblePlayEvents :many
SELECT id, play_id, event_type, actor_user_id, actor_display_name, subject_user_id, subject_display_name, participant_id, metadata, created_at FROM (
    SELECT id, play_id, event_type, actor_user_id, actor_display_name, subject_user_id, subject_display_name, participant_id, metadata, created_at
    FROM play_events
    WHERE play_id = ?
      -- Roster events only: pending-queue events (requests, waitlist moves,
      -- withdrawals) carry identities that are host-only, like the queue itself
      AND event_type IN (
        'participant.joined',
        'participant.added',
        'participant.confirmed',
        'participant.left_confirmed',
        'participant.left_added',
        'play.cancelled',
        'play.updated'
      )
    ORDER BY created_at DESC, id DESC
    LIMIT ?
)
ORDER BY created_at ASC, id ASC
`

type ListParticipantVisiblePlayEventsParams struct {
	PlayID string
	Limit  int64
}

func (q *Queries) ListParticipantVisiblePlayEvents(ctx context.Context, arg ListParticipantVisiblePlayEventsParams) ([]PlayEvent, error) {
	rows, err := q.db.QueryContext(ctx, listParticipantVisiblePlayEvents, arg.PlayID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlayEvent
	for rows.Next() {
		var i PlayEvent
		if err := rows.Scan(
			&i.ID,
			&i.PlayID,
			&i.EventType,
			&i.ActorUserID,
			&i.ActorDisplayName,
			&i.SubjectUserID,
			&i.SubjectDisplayName,
			&i.ParticipantID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
