// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: raw_messages.sql

package db

import (
	"context"
	"time"
)

const getPendingJob = `-- name: GetPendingJob :one
SELECT id, created_at, updated_at, source, sender_username, message_text, message_time, content_hash, status, retry_count, next_retry_at, last_error, llm_response
FROM raw_messages
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT 1
`

func (q *Queries) GetPendingJob(ctx context.Context) (RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getPendingJob)
	var i RawMessage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.SenderUsername,
		&i.MessageText,
		&i.MessageTime,
		&i.ContentHash,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.LlmResponse,
	)
	return i, err
}

const getRecentMessageTexts = `-- name: GetRecentMessageTexts :many
SELECT id, message_text
FROM raw_messages
WHERE created_at > ?
  AND status != 'skipped'
`

type GetRecentMessageTextsRow struct {
	ID          int64
	MessageText string
}

func (q *Queries) GetRecentMessageTexts(ctx context.Context, createdAt time.Time) ([]GetRecentMessageTextsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentMessageTexts, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentMessageTextsRow
	for rows.Next() {
		var i GetRecentMessageTextsRow
		if err := rows.Scan(&i.ID, &i.MessageText); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetryJob = `-- name: GetRetryJob :one
SELECT id, created_at, updated_at, source, sender_username, message_text, message_time, content_hash, status, retry_count, next_retry_at, last_error, llm_response
FROM raw_messages
WHERE status = 'failed' AND next_retry_at <= CURRENT_TIMESTAMP
ORDER BY next_retry_at ASC
LIMIT 1
`

func (q *Queries) GetRetryJob(ctx context.Context) (RawMessage, error) {
	row := q.db.QueryRowContext(ctx, getRetryJob)
	var i RawMessage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.SenderUsername,
		&i.MessageText,
		&i.MessageTime,
		&i.ContentHash,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.LlmResponse,
	)
	return i, err
}

const insertRawMessage = `-- name: InsertRawMessage :one
INSERT INTO raw_messages (source, sender_username, message_text, message_time, content_hash, status)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, source, sender_username, message_text, message_time, content_hash, status, retry_count, next_retry_at, last_error, llm_response
`

type InsertRawMessageParams struct {
	Source         string
	SenderUsername string
	MessageText    string
	MessageTime    time.Time
	ContentHash    string
	Status         string
}

func (q *Queries) InsertRawMessage(ctx context.Context, arg InsertRawMessageParams) (RawMessage, error) {
	row := q.db.QueryRowContext(ctx, insertRawMessage,
		arg.Source,
		arg.SenderUsername,
		arg.MessageText,
		arg.MessageTime,
		arg.ContentHash,
		arg.Status,
	)
	var i RawMessage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.SenderUsername,
		&i.MessageText,
		&i.MessageTime,
		&i.ContentHash,
		&i.Status,
		&i.RetryCount,
		&i.NextRetryAt,
		&i.LastError,
		&i.LlmResponse,
	)
	return i, err
}

const markDone = `-- name: MarkDone :exec
UPDATE raw_messages
SET status = 'done', llm_response = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MarkDoneParams struct {
	LlmResponse *string
	ID          int64
}

func (q *Queries) MarkDone(ctx context.Context, arg MarkDoneParams) error {
	_, err := q.db.ExecContext(ctx, markDone, arg.LlmResponse, arg.ID)
	return err
}

const markFailed = `-- name: MarkFailed :exec
UPDATE raw_messages
SET status = 'failed',
    retry_count = retry_count + 1,
    next_retry_at = ?,
    last_error = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type MarkFailedParams struct {
	NextRetryAt *time.Time
	LastError   *string
	ID          int64
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) error {
	_, err := q.db.ExecContext(ctx, markFailed, arg.NextRetryAt, arg.LastError, arg.ID)
	return err
}

const markProcessing = `-- name: MarkProcessing :exec
UPDATE raw_messages
SET status = 'processing', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkProcessing(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markProcessing, id)
	return err
}

const markSkipped = `-- name: MarkSkipped :exec
UPDATE raw_messages
SET status = 'skipped', updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkSkipped(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSkipped, id)
	return err
}
