// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"
)

const createBlock = `-- name: CreateBlock :exec
INSERT OR IGNORE INTO user_blocks (blocker_id, blocked_id) VALUES (?, ?)
`

type CreateBlockParams struct {
	BlockerID string
	BlockedID string
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.ExecContext(ctx, createBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM user_blocks WHERE blocker_id = ? AND blocked_id = ?
`

type DeleteBlockParams struct {
	BlockerID string
	BlockedID string
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.token,
    s.user_id,
    s.expires_at,
    u.id AS user_id_2,
    u.email,
    u.username,
    u.display_name,
    u.photo_url,
    u.google_id,
    u.facebook_id,
    u.status,
    u.sports_profile,
    u.contact_info,
    u.created_at,
    u.updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = ? AND s.expires_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
`

type GetSessionWithUserRow struct {
	Token         string
	UserID        string
	ExpiresAt     time.Time
	UserID2       string
	Email         string
	Username      *string
	DisplayName   string
	PhotoUrl      *string
	GoogleID      *string
	FacebookID    *string
	Status        string
	SportsProfile *string
	ContactInfo   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, token)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.UserID2,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS(
    SELECT 1 FROM user_blocks
    WHERE (blocker_id = ? AND blocked_id = ?)
       OR (blocker_id = ? AND blocked_id = ?)
) AS is_blocked
`

type IsBlockedParams struct {
	BlockerID   string
	BlockedID   string
	BlockerID_2 string
	BlockedID_2 string
}

// Returns 1 if either user blocked the other (mutual check for hide logic)
func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isBlocked,
		arg.BlockerID,
		arg.BlockedID,
		arg.BlockerID_2,
		arg.BlockedID_2,
	)
	var is_blocked int64
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const linkFacebookID = `-- name: LinkFacebookID :one
UPDATE users SET facebook_id = ?, updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE email = ? AND facebook_id IS NULL
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at
`

type LinkFacebookIDParams struct {
	FacebookID *string
	Email      string
}

func (q *Queries) LinkFacebookID(ctx context.Context, arg LinkFacebookIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, linkFacebookID, arg.FacebookID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :one
UPDATE users SET google_id = ?, updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE email = ? AND google_id IS NULL
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at
`

type LinkGoogleIDParams struct {
	GoogleID *string
	Email    string
}

func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, linkGoogleID, arg.GoogleID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBlockedUserIDs = `-- name: ListBlockedUserIDs :many
SELECT blocked_id FROM user_blocks WHERE blocker_id = ?
`

func (q *Queries) ListBlockedUserIDs(ctx context.Context, blockerID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedUserIDs, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blocked_id string
		if err := rows.Scan(&blocked_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshSession = `-- name: RefreshSession :exec
UPDATE sessions SET expires_at = ? WHERE token = ?
`

type RefreshSessionParams struct {
	ExpiresAt time.Time
	Token     string
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) error {
	_, err := q.db.ExecContext(ctx, refreshSession, arg.ExpiresAt, arg.Token)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    display_name = ?,
    username = ?,
    photo_url = ?,
    sports_profile = ?,
    contact_info = ?,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName   string
	Username      *string
	PhotoUrl      *string
	SportsProfile *string
	ContactInfo   *string
	ID            string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Username,
		arg.PhotoUrl,
		arg.SportsProfile,
		arg.ContactInfo,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET
    status = ?,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.ID)
	return err
}

const upsertUserByFacebookID = `-- name: UpsertUserByFacebookID :one
INSERT INTO users (id, email, display_name, photo_url, facebook_id, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%d %H:%M:%S+00:00', 'now'))
ON CONFLICT(facebook_id) DO UPDATE SET
    email = excluded.email,
    display_name = excluded.display_name,
    photo_url = excluded.photo_url,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at
`

type UpsertUserByFacebookIDParams struct {
	ID          string
	Email       string
	DisplayName string
	PhotoUrl    *string
	FacebookID  *string
}

func (q *Queries) UpsertUserByFacebookID(ctx context.Context, arg UpsertUserByFacebookIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByFacebookID,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PhotoUrl,
		arg.FacebookID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserByGoogleID = `-- name: UpsertUserByGoogleID :one
INSERT INTO users (id, email, display_name, photo_url, google_id, updated_at)
VALUES (?, ?, ?, ?, ?, strftime('%Y-%m-%d %H:%M:%S+00:00', 'now'))
ON CONFLICT(google_id) DO UPDATE SET
    email = excluded.email,
    display_name = excluded.display_name,
    photo_url = excluded.photo_url,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at
`

type UpsertUserByGoogleIDParams struct {
	ID          string
	Email       string
	DisplayName string
	PhotoUrl    *string
	GoogleID    *string
}

func (q *Queries) UpsertUserByGoogleID(ctx context.Context, arg UpsertUserByGoogleIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByGoogleID,
		arg.ID,
		arg.Email,
		arg.DisplayName,
		arg.PhotoUrl,
		arg.GoogleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
