// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"openplays/server/internal/model"
)

const clearUserAvatar = `-- name: ClearUserAvatar :one
UPDATE users SET
    photo_url = oauth_photo_url,
    avatar_key = NULL,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?1
  AND avatar_key IS ?2
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key
`

type ClearUserAvatarParams struct {
	ID                string
	ExpectedAvatarKey *string
}

func (q *Queries) ClearUserAvatar(ctx context.Context, arg ClearUserAvatarParams) (User, error) {
	row := q.db.QueryRowContext(ctx, clearUserAvatar, arg.ID, arg.ExpectedAvatarKey)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}

const countRosteredPlaysByUser = `-- name: CountRosteredPlaysByUser :one
SELECT COUNT(DISTINCT play_id)
FROM (
    SELECT play_id
    FROM play_hosts ph
    WHERE ph.user_id = ?1
    UNION
    SELECT play_id
    FROM play_participants pp
    WHERE pp.user_id = ?1 AND pp.status IN ('confirmed', 'added')
)
`

func (q *Queries) CountRosteredPlaysByUser(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRosteredPlaysByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRosteredPlaysByUserAndSport = `-- name: CountRosteredPlaysByUserAndSport :many
WITH rostered_play_ids AS (
    SELECT play_id
    FROM play_hosts ph
    WHERE ph.user_id = ?1
    UNION
    SELECT play_id
    FROM play_participants pp
    WHERE pp.user_id = ?1 AND pp.status IN ('confirmed', 'added')
)
SELECT p.sport, COUNT(DISTINCT p.id) AS play_count
FROM plays p
JOIN rostered_play_ids r ON r.play_id = p.id
GROUP BY p.sport
ORDER BY p.sport ASC
`

type CountRosteredPlaysByUserAndSportRow struct {
	Sport     model.Sport
	PlayCount int64
}

func (q *Queries) CountRosteredPlaysByUserAndSport(ctx context.Context, userID string) ([]CountRosteredPlaysByUserAndSportRow, error) {
	rows, err := q.db.QueryContext(ctx, countRosteredPlaysByUserAndSport, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountRosteredPlaysByUserAndSportRow
	for rows.Next() {
		var i CountRosteredPlaysByUserAndSportRow
		if err := rows.Scan(&i.Sport, &i.PlayCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBlock = `-- name: CreateBlock :exec
INSERT OR IGNORE INTO user_blocks (blocker_id, blocked_id) VALUES (?, ?)
`

type CreateBlockParams struct {
	BlockerID string
	BlockedID string
}

func (q *Queries) CreateBlock(ctx context.Context, arg CreateBlockParams) error {
	_, err := q.db.ExecContext(ctx, createBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string
	UserID    string
	ExpiresAt time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteBlock = `-- name: DeleteBlock :exec
DELETE FROM user_blocks WHERE blocker_id = ? AND blocked_id = ?
`

type DeleteBlockParams struct {
	BlockerID string
	BlockedID string
}

func (q *Queries) DeleteBlock(ctx context.Context, arg DeleteBlockParams) error {
	_, err := q.db.ExecContext(ctx, deleteBlock, arg.BlockerID, arg.BlockedID)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions WHERE user_id = ?
`

func (q *Queries) DeleteUserSessions(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getActiveUserProfileByUsername = `-- name: GetActiveUserProfileByUsername :one
SELECT id, display_name, username, photo_url, sports_profile
FROM users
WHERE username = ? AND status = 'active'
`

type GetActiveUserProfileByUsernameRow struct {
	ID            string
	DisplayName   string
	Username      *string
	PhotoUrl      *string
	SportsProfile *string
}

func (q *Queries) GetActiveUserProfileByUsername(ctx context.Context, username *string) (GetActiveUserProfileByUsernameRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveUserProfileByUsername, username)
	var i GetActiveUserProfileByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Username,
		&i.PhotoUrl,
		&i.SportsProfile,
	)
	return i, err
}

const getSessionWithUser = `-- name: GetSessionWithUser :one
SELECT
    s.token,
    s.user_id,
    s.expires_at,
    u.id AS user_id_2,
    u.email,
    u.username,
    u.display_name,
    u.photo_url,
    u.google_id,
    u.facebook_id,
    u.status,
    u.sports_profile,
    u.contact_info,
    u.created_at,
    u.updated_at
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = ? AND s.expires_at > strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
`

type GetSessionWithUserRow struct {
	Token         string
	UserID        string
	ExpiresAt     time.Time
	UserID2       string
	Email         string
	Username      *string
	DisplayName   string
	PhotoUrl      *string
	GoogleID      *string
	FacebookID    *string
	Status        string
	SportsProfile *string
	ContactInfo   *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

func (q *Queries) GetSessionWithUser(ctx context.Context, token string) (GetSessionWithUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionWithUser, token)
	var i GetSessionWithUserRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.UserID2,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key FROM users WHERE id = ?
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}

const isBlocked = `-- name: IsBlocked :one
SELECT EXISTS(
    SELECT 1 FROM user_blocks
    WHERE (blocker_id = ? AND blocked_id = ?)
       OR (blocker_id = ? AND blocked_id = ?)
) AS is_blocked
`

type IsBlockedParams struct {
	BlockerID   string
	BlockedID   string
	BlockerID_2 string
	BlockedID_2 string
}

// Returns 1 if either user blocked the other (mutual check for hide logic)
func (q *Queries) IsBlocked(ctx context.Context, arg IsBlockedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isBlocked,
		arg.BlockerID,
		arg.BlockedID,
		arg.BlockerID_2,
		arg.BlockedID_2,
	)
	var is_blocked bool
	err := row.Scan(&is_blocked)
	return is_blocked, err
}

const linkFacebookID = `-- name: LinkFacebookID :one
UPDATE users SET facebook_id = ?, updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE email = ? AND facebook_id IS NULL
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key
`

type LinkFacebookIDParams struct {
	FacebookID *string
	Email      string
}

func (q *Queries) LinkFacebookID(ctx context.Context, arg LinkFacebookIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, linkFacebookID, arg.FacebookID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}

const linkGoogleID = `-- name: LinkGoogleID :one
UPDATE users SET google_id = ?, updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE email = ? AND google_id IS NULL
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key
`

type LinkGoogleIDParams struct {
	GoogleID *string
	Email    string
}

func (q *Queries) LinkGoogleID(ctx context.Context, arg LinkGoogleIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, linkGoogleID, arg.GoogleID, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}

const listBlockedUserIDs = `-- name: ListBlockedUserIDs :many
SELECT blocked_id FROM user_blocks WHERE blocker_id = ?
`

func (q *Queries) ListBlockedUserIDs(ctx context.Context, blockerID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listBlockedUserIDs, blockerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var blocked_id string
		if err := rows.Scan(&blocked_id); err != nil {
			return nil, err
		}
		items = append(items, blocked_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshSession = `-- name: RefreshSession :exec
UPDATE sessions SET expires_at = ? WHERE token = ?
`

type RefreshSessionParams struct {
	ExpiresAt time.Time
	Token     string
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) error {
	_, err := q.db.ExecContext(ctx, refreshSession, arg.ExpiresAt, arg.Token)
	return err
}

const searchActiveUsers = `-- name: SearchActiveUsers :many
SELECT id, display_name, username, photo_url, sports_profile
FROM users
WHERE status = 'active'
  AND (
    ?1 = ''
    OR lower(display_name) LIKE '%' || lower(?1) || '%'
    OR lower(COALESCE(username, '')) LIKE '%' || lower(?1) || '%'
  )
ORDER BY display_name ASC, id ASC
LIMIT ?2
`

type SearchActiveUsersParams struct {
	Query interface{}
	Limit int64
}

type SearchActiveUsersRow struct {
	ID            string
	DisplayName   string
	Username      *string
	PhotoUrl      *string
	SportsProfile *string
}

func (q *Queries) SearchActiveUsers(ctx context.Context, arg SearchActiveUsersParams) ([]SearchActiveUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, searchActiveUsers, arg.Query, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchActiveUsersRow
	for rows.Next() {
		var i SearchActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Username,
			&i.PhotoUrl,
			&i.SportsProfile,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserAvatar = `-- name: SetUserAvatar :one
UPDATE users SET
    photo_url = ?1,
    avatar_key = ?2,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?3
  AND avatar_key IS ?4
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key
`

type SetUserAvatarParams struct {
	PhotoUrl          *string
	AvatarKey         *string
	ID                string
	ExpectedAvatarKey *string
}

func (q *Queries) SetUserAvatar(ctx context.Context, arg SetUserAvatarParams) (User, error) {
	row := q.db.QueryRowContext(ctx, setUserAvatar,
		arg.PhotoUrl,
		arg.AvatarKey,
		arg.ID,
		arg.ExpectedAvatarKey,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    display_name = ?,
    username = ?,
    sports_profile = ?,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key
`

type UpdateUserProfileParams struct {
	DisplayName   string
	Username      *string
	SportsProfile *string
	ID            string
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserProfile,
		arg.DisplayName,
		arg.Username,
		arg.SportsProfile,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users SET
    status = ?,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
WHERE id = ?
`

type UpdateUserStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateUserStatus, arg.Status, arg.ID)
	return err
}

const upsertUserByFacebookID = `-- name: UpsertUserByFacebookID :one
INSERT INTO users (id, email, username, display_name, photo_url, oauth_photo_url, facebook_id, updated_at)
VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
)
ON CONFLICT(facebook_id) DO UPDATE SET
    email = excluded.email,
    display_name = excluded.display_name,
    oauth_photo_url = excluded.oauth_photo_url,
    photo_url = CASE
        WHEN users.avatar_key IS NULL THEN excluded.oauth_photo_url
        ELSE users.photo_url
    END,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key
`

type UpsertUserByFacebookIDParams struct {
	ID            string
	Email         string
	Username      *string
	DisplayName   string
	PhotoUrl      *string
	OauthPhotoUrl *string
	FacebookID    *string
}

func (q *Queries) UpsertUserByFacebookID(ctx context.Context, arg UpsertUserByFacebookIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByFacebookID,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PhotoUrl,
		arg.OauthPhotoUrl,
		arg.FacebookID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}

const upsertUserByGoogleID = `-- name: UpsertUserByGoogleID :one
INSERT INTO users (id, email, username, display_name, photo_url, oauth_photo_url, google_id, updated_at)
VALUES (
    ?1, ?2, ?3, ?4,
    ?5, ?6, ?7,
    strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
)
ON CONFLICT(google_id) DO UPDATE SET
    email = excluded.email,
    display_name = excluded.display_name,
    oauth_photo_url = excluded.oauth_photo_url,
    photo_url = CASE
        WHEN users.avatar_key IS NULL THEN excluded.oauth_photo_url
        ELSE users.photo_url
    END,
    updated_at = strftime('%Y-%m-%d %H:%M:%S+00:00', 'now')
RETURNING id, email, username, display_name, photo_url, google_id, facebook_id, status, sports_profile, contact_info, created_at, updated_at, oauth_photo_url, avatar_key
`

type UpsertUserByGoogleIDParams struct {
	ID            string
	Email         string
	Username      *string
	DisplayName   string
	PhotoUrl      *string
	OauthPhotoUrl *string
	GoogleID      *string
}

func (q *Queries) UpsertUserByGoogleID(ctx context.Context, arg UpsertUserByGoogleIDParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUserByGoogleID,
		arg.ID,
		arg.Email,
		arg.Username,
		arg.DisplayName,
		arg.PhotoUrl,
		arg.OauthPhotoUrl,
		arg.GoogleID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.DisplayName,
		&i.PhotoUrl,
		&i.GoogleID,
		&i.FacebookID,
		&i.Status,
		&i.SportsProfile,
		&i.ContactInfo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.OauthPhotoUrl,
		&i.AvatarKey,
	)
	return i, err
}
