// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package db

import (
	"context"
)

const getVenueByAlias = `-- name: GetVenueByAlias :one
SELECT v.id, v.postal_code, v.name, v.address, v.latitude, v.longitude, v.source, v.search_term
FROM venues v
JOIN venue_aliases va ON va.venue_id = v.id
WHERE va.alias = ?
`

func (q *Queries) GetVenueByAlias(ctx context.Context, alias string) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenueByAlias, alias)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.PostalCode,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
		&i.SearchTerm,
	)
	return i, err
}

const getVenueByID = `-- name: GetVenueByID :one
SELECT id, postal_code, name, address, latitude, longitude, source, search_term FROM venues WHERE id = ?
`

func (q *Queries) GetVenueByID(ctx context.Context, id int64) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenueByID, id)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.PostalCode,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
		&i.SearchTerm,
	)
	return i, err
}

const listAliases = `-- name: ListAliases :many
SELECT va.alias, va.venue_id, v.name AS venue_name
FROM venue_aliases va
JOIN venues v ON v.id = va.venue_id
ORDER BY va.alias
`

type ListAliasesRow struct {
	Alias     string
	VenueID   int64
	VenueName string
}

func (q *Queries) ListAliases(ctx context.Context) ([]ListAliasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAliasesRow
	for rows.Next() {
		var i ListAliasesRow
		if err := rows.Scan(&i.Alias, &i.VenueID, &i.VenueName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenueNames = `-- name: ListVenueNames :many
SELECT id, name FROM venues
`

type ListVenueNamesRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListVenueNames(ctx context.Context) ([]ListVenueNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listVenueNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVenueNamesRow
	for rows.Next() {
		var i ListVenueNamesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVenues = `-- name: ListVenues :many
SELECT id, postal_code, name, address, latitude, longitude, source, search_term FROM venues
ORDER BY name
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.ID,
			&i.PostalCode,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Source,
			&i.SearchTerm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVenue = `-- name: UpsertVenue :one
INSERT INTO venues (postal_code, name, address, latitude, longitude, source, search_term)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(postal_code) DO UPDATE SET
    name        = excluded.name,
    address     = excluded.address,
    latitude    = excluded.latitude,
    longitude   = excluded.longitude,
    source      = excluded.source
RETURNING id, postal_code, name, address, latitude, longitude, source, search_term
`

type UpsertVenueParams struct {
	PostalCode *string
	Name       string
	Address    string
	Latitude   float64
	Longitude  float64
	Source     string
	SearchTerm *string
}

// For venues with a postal code, upsert on postal_code.
// For venues without (generic locations), always insert a new row.
func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, upsertVenue,
		arg.PostalCode,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Source,
		arg.SearchTerm,
	)
	var i Venue
	err := row.Scan(
		&i.ID,
		&i.PostalCode,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
		&i.SearchTerm,
	)
	return i, err
}

const upsertVenueAlias = `-- name: UpsertVenueAlias :exec
INSERT INTO venue_aliases (alias, venue_id)
VALUES (?, ?)
ON CONFLICT(alias) DO UPDATE SET
    venue_id = excluded.venue_id
`

type UpsertVenueAliasParams struct {
	Alias   string
	VenueID int64
}

func (q *Queries) UpsertVenueAlias(ctx context.Context, arg UpsertVenueAliasParams) error {
	_, err := q.db.ExecContext(ctx, upsertVenueAlias, arg.Alias, arg.VenueID)
	return err
}
