// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: venues.sql

package db

import (
	"context"
)

const getVenueByAlias = `-- name: GetVenueByAlias :one
SELECT v.postal_code, v.name, v.address, v.latitude, v.longitude, v.source
FROM venues v
JOIN venue_aliases va ON va.venue_postal_code = v.postal_code
WHERE va.alias = ?
`

func (q *Queries) GetVenueByAlias(ctx context.Context, alias string) (Venue, error) {
	row := q.db.QueryRowContext(ctx, getVenueByAlias, alias)
	var i Venue
	err := row.Scan(
		&i.PostalCode,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
	)
	return i, err
}

const insertAlias = `-- name: InsertAlias :exec
INSERT INTO venue_aliases (alias, venue_postal_code)
VALUES (?, ?)
ON CONFLICT(alias) DO NOTHING
`

type InsertAliasParams struct {
	Alias           string
	VenuePostalCode string
}

func (q *Queries) InsertAlias(ctx context.Context, arg InsertAliasParams) error {
	_, err := q.db.ExecContext(ctx, insertAlias, arg.Alias, arg.VenuePostalCode)
	return err
}

const listVenues = `-- name: ListVenues :many
SELECT postal_code, name, address, latitude, longitude, source FROM venues
ORDER BY name
`

func (q *Queries) ListVenues(ctx context.Context) ([]Venue, error) {
	rows, err := q.db.QueryContext(ctx, listVenues)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Venue
	for rows.Next() {
		var i Venue
		if err := rows.Scan(
			&i.PostalCode,
			&i.Name,
			&i.Address,
			&i.Latitude,
			&i.Longitude,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVenue = `-- name: UpsertVenue :one
INSERT INTO venues (postal_code, name, address, latitude, longitude, source)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(postal_code) DO UPDATE SET
    name      = excluded.name,
    address   = excluded.address,
    latitude  = excluded.latitude,
    longitude = excluded.longitude,
    source    = excluded.source
RETURNING postal_code, name, address, latitude, longitude, source
`

type UpsertVenueParams struct {
	PostalCode string
	Name       string
	Address    string
	Latitude   float64
	Longitude  float64
	Source     string
}

func (q *Queries) UpsertVenue(ctx context.Context, arg UpsertVenueParams) (Venue, error) {
	row := q.db.QueryRowContext(ctx, upsertVenue,
		arg.PostalCode,
		arg.Name,
		arg.Address,
		arg.Latitude,
		arg.Longitude,
		arg.Source,
	)
	var i Venue
	err := row.Scan(
		&i.PostalCode,
		&i.Name,
		&i.Address,
		&i.Latitude,
		&i.Longitude,
		&i.Source,
	)
	return i, err
}
